// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from build/libfwupd
// from build/libfwupdplugin
// DO NOT EDIT

#![cfg(unix)]

use fwupd_sys::*;
use std::mem::{align_of, size_of};
use std::env;
use std::error::Error;
use std::ffi::OsString;
use std::path::Path;
use std::process::{Command, Stdio};
use std::str;
use tempfile::Builder;

static PACKAGES: &[&str] = &["fwupd"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Self, Box<dyn Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        // For _Generic
        args.push("-std=c11".to_owned());
        // For %z support in printf when using MinGW.
        args.push("-D__USE_MINGW_ANSI_STDIO".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Self { args })
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {cmd:?} failed, {status}").into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<dyn Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{name} {err}").into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<dyn Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let pkg_config = env::var_os("PKG_CONFIG")
        .unwrap_or_else(|| OsString::from("pkg-config"));
    let mut cmd = Command::new(pkg_config);
    cmd.arg("--cflags");
    cmd.args(packages);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}


#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn summary(&self) -> String {
        format!("{} passed; {} failed", self.passed, self.failed)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let mut c_constants: Vec<(String, String)> = Vec::new();

    for l in get_c_output("constant").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing ';' separator");
        c_constants.push((name.to_owned(), value.to_owned()));
    }

    let mut results = Results::default();

    for ((rust_name, rust_value), (c_name, c_value)) in
        RUST_CONSTANTS.iter().zip(c_constants.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_value != c_value {
            results.record_failed();
            eprintln!(
                "Constant value mismatch for {rust_name}\nRust: {rust_value:?}\nC:    {c_value:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let mut c_layouts = Vec::new();

    for l in get_c_output("layout").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing first ';' separator");
        let (size, alignment) = value.split_once(';').expect("Missing second ';' separator");
        let size = size.parse().expect("Failed to parse size");
        let alignment = alignment.parse().expect("Failed to parse alignment");
        c_layouts.push((name.to_owned(), Layout { size, alignment }));
    }

    let mut results = Results::default();

    for ((rust_name, rust_layout), (c_name, c_layout)) in
        RUST_LAYOUTS.iter().zip(c_layouts.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_layout != c_layout {
            results.record_failed();
            eprintln!(
                "Layout mismatch for {rust_name}\nRust: {rust_layout:?}\nC:    {c_layout:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

fn get_c_output(name: &str) -> Result<String, Box<dyn Error>> {
    let tmpdir = Builder::new().prefix("abi").tempdir()?;
    let exe = tmpdir.path().join(name);
    let c_file = Path::new("tests").join(name).with_extension("c");

    let cc = Compiler::new().expect("configured compiler");
    cc.compile(&c_file, &exe)?;

    let mut cmd = Command::new(exe);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }

    Ok(String::from_utf8(out.stdout)?)
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    ("FwupdBiosSetting", Layout {size: size_of::<FwupdBiosSetting>(), alignment: align_of::<FwupdBiosSetting>()}),
    ("FwupdBiosSettingClass", Layout {size: size_of::<FwupdBiosSettingClass>(), alignment: align_of::<FwupdBiosSettingClass>()}),
    ("FwupdBiosSettingKind", Layout {size: size_of::<FwupdBiosSettingKind>(), alignment: align_of::<FwupdBiosSettingKind>()}),
    ("FwupdClient", Layout {size: size_of::<FwupdClient>(), alignment: align_of::<FwupdClient>()}),
    ("FwupdClientClass", Layout {size: size_of::<FwupdClientClass>(), alignment: align_of::<FwupdClientClass>()}),
    ("FwupdClientDownloadFlags", Layout {size: size_of::<FwupdClientDownloadFlags>(), alignment: align_of::<FwupdClientDownloadFlags>()}),
    ("FwupdClientUploadFlags", Layout {size: size_of::<FwupdClientUploadFlags>(), alignment: align_of::<FwupdClientUploadFlags>()}),
    ("FwupdCodecFlags", Layout {size: size_of::<FwupdCodecFlags>(), alignment: align_of::<FwupdCodecFlags>()}),
    ("FwupdCodecInterface", Layout {size: size_of::<FwupdCodecInterface>(), alignment: align_of::<FwupdCodecInterface>()}),
    ("FwupdDevice", Layout {size: size_of::<FwupdDevice>(), alignment: align_of::<FwupdDevice>()}),
    ("FwupdDeviceClass", Layout {size: size_of::<FwupdDeviceClass>(), alignment: align_of::<FwupdDeviceClass>()}),
    ("FwupdDeviceFlags", Layout {size: size_of::<FwupdDeviceFlags>(), alignment: align_of::<FwupdDeviceFlags>()}),
    ("FwupdDeviceProblem", Layout {size: size_of::<FwupdDeviceProblem>(), alignment: align_of::<FwupdDeviceProblem>()}),
    ("FwupdError", Layout {size: size_of::<FwupdError>(), alignment: align_of::<FwupdError>()}),
    ("FwupdFeatureFlags", Layout {size: size_of::<FwupdFeatureFlags>(), alignment: align_of::<FwupdFeatureFlags>()}),
    ("FwupdGuidFlags", Layout {size: size_of::<FwupdGuidFlags>(), alignment: align_of::<FwupdGuidFlags>()}),
    ("FwupdInstallFlags", Layout {size: size_of::<FwupdInstallFlags>(), alignment: align_of::<FwupdInstallFlags>()}),
    ("FwupdJsonExportFlags", Layout {size: size_of::<FwupdJsonExportFlags>(), alignment: align_of::<FwupdJsonExportFlags>()}),
    ("FwupdJsonLoadFlags", Layout {size: size_of::<FwupdJsonLoadFlags>(), alignment: align_of::<FwupdJsonLoadFlags>()}),
    ("FwupdJsonNodeKind", Layout {size: size_of::<FwupdJsonNodeKind>(), alignment: align_of::<FwupdJsonNodeKind>()}),
    ("FwupdJsonParserClass", Layout {size: size_of::<FwupdJsonParserClass>(), alignment: align_of::<FwupdJsonParserClass>()}),
    ("FwupdPlugin", Layout {size: size_of::<FwupdPlugin>(), alignment: align_of::<FwupdPlugin>()}),
    ("FwupdPluginClass", Layout {size: size_of::<FwupdPluginClass>(), alignment: align_of::<FwupdPluginClass>()}),
    ("FwupdPluginFlags", Layout {size: size_of::<FwupdPluginFlags>(), alignment: align_of::<FwupdPluginFlags>()}),
    ("FwupdRelease", Layout {size: size_of::<FwupdRelease>(), alignment: align_of::<FwupdRelease>()}),
    ("FwupdReleaseClass", Layout {size: size_of::<FwupdReleaseClass>(), alignment: align_of::<FwupdReleaseClass>()}),
    ("FwupdReleaseFlags", Layout {size: size_of::<FwupdReleaseFlags>(), alignment: align_of::<FwupdReleaseFlags>()}),
    ("FwupdReleaseUrgency", Layout {size: size_of::<FwupdReleaseUrgency>(), alignment: align_of::<FwupdReleaseUrgency>()}),
    ("FwupdRemote", Layout {size: size_of::<FwupdRemote>(), alignment: align_of::<FwupdRemote>()}),
    ("FwupdRemoteClass", Layout {size: size_of::<FwupdRemoteClass>(), alignment: align_of::<FwupdRemoteClass>()}),
    ("FwupdRemoteFlags", Layout {size: size_of::<FwupdRemoteFlags>(), alignment: align_of::<FwupdRemoteFlags>()}),
    ("FwupdRemoteKind", Layout {size: size_of::<FwupdRemoteKind>(), alignment: align_of::<FwupdRemoteKind>()}),
    ("FwupdReport", Layout {size: size_of::<FwupdReport>(), alignment: align_of::<FwupdReport>()}),
    ("FwupdReportClass", Layout {size: size_of::<FwupdReportClass>(), alignment: align_of::<FwupdReportClass>()}),
    ("FwupdReportFlags", Layout {size: size_of::<FwupdReportFlags>(), alignment: align_of::<FwupdReportFlags>()}),
    ("FwupdRequest", Layout {size: size_of::<FwupdRequest>(), alignment: align_of::<FwupdRequest>()}),
    ("FwupdRequestClass", Layout {size: size_of::<FwupdRequestClass>(), alignment: align_of::<FwupdRequestClass>()}),
    ("FwupdRequestFlags", Layout {size: size_of::<FwupdRequestFlags>(), alignment: align_of::<FwupdRequestFlags>()}),
    ("FwupdRequestKind", Layout {size: size_of::<FwupdRequestKind>(), alignment: align_of::<FwupdRequestKind>()}),
    ("FwupdSecurityAttr", Layout {size: size_of::<FwupdSecurityAttr>(), alignment: align_of::<FwupdSecurityAttr>()}),
    ("FwupdSecurityAttrClass", Layout {size: size_of::<FwupdSecurityAttrClass>(), alignment: align_of::<FwupdSecurityAttrClass>()}),
    ("FwupdSecurityAttrFlags", Layout {size: size_of::<FwupdSecurityAttrFlags>(), alignment: align_of::<FwupdSecurityAttrFlags>()}),
    ("FwupdSecurityAttrLevel", Layout {size: size_of::<FwupdSecurityAttrLevel>(), alignment: align_of::<FwupdSecurityAttrLevel>()}),
    ("FwupdSecurityAttrResult", Layout {size: size_of::<FwupdSecurityAttrResult>(), alignment: align_of::<FwupdSecurityAttrResult>()}),
    ("FwupdSelfSignFlags", Layout {size: size_of::<FwupdSelfSignFlags>(), alignment: align_of::<FwupdSelfSignFlags>()}),
    ("FwupdStatus", Layout {size: size_of::<FwupdStatus>(), alignment: align_of::<FwupdStatus>()}),
    ("FwupdUpdateState", Layout {size: size_of::<FwupdUpdateState>(), alignment: align_of::<FwupdUpdateState>()}),
    ("FwupdVersionFormat", Layout {size: size_of::<FwupdVersionFormat>(), alignment: align_of::<FwupdVersionFormat>()}),
    ("fwupd_guid_t", Layout {size: size_of::<fwupd_guid_t>(), alignment: align_of::<fwupd_guid_t>()}),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("FWUPD_BATTERY_LEVEL_INVALID", "101"),
    ("FWUPD_BIOS_SETTING_DEBUG_CMD", "debug_cmd"),
    ("(gint) FWUPD_BIOS_SETTING_KIND_ENUMERATION", "1"),
    ("(gint) FWUPD_BIOS_SETTING_KIND_INTEGER", "2"),
    ("FWUPD_BIOS_SETTING_KIND_LAST", "4"),
    ("(gint) FWUPD_BIOS_SETTING_KIND_STRING", "3"),
    ("(gint) FWUPD_BIOS_SETTING_KIND_UNKNOWN", "0"),
    ("FWUPD_BIOS_SETTING_PENDING_REBOOT", "pending_reboot"),
    ("FWUPD_BIOS_SETTING_RESET_BIOS", "reset_bios"),
    ("FWUPD_BIOS_SETTING_SELF_TEST", "fwupd_self_test"),
    ("(guint) FWUPD_CLIENT_DOWNLOAD_FLAG_NONE", "0"),
    ("(guint) FWUPD_CLIENT_DOWNLOAD_FLAG_ONLY_P2P", "1"),
    ("(guint) FWUPD_CLIENT_UPLOAD_FLAG_ALWAYS_MULTIPART", "1"),
    ("(guint) FWUPD_CLIENT_UPLOAD_FLAG_NONE", "0"),
    ("(guint) FWUPD_CODEC_FLAG_COMPRESSED", "2"),
    ("(guint) FWUPD_CODEC_FLAG_NONE", "0"),
    ("(guint) FWUPD_CODEC_FLAG_TRUSTED", "1"),
    ("FWUPD_DBUS_INTERFACE", "org.freedesktop.fwupd"),
    ("FWUPD_DBUS_PATH", "/"),
    ("FWUPD_DBUS_SERVICE", "org.freedesktop.fwupd"),
    ("(guint64) FWUPD_DEVICE_FLAG_AFFECTS_FDE", "35184372088832"),
    ("(guint64) FWUPD_DEVICE_FLAG_ANOTHER_WRITE_REQUIRED", "262144"),
    ("(guint64) FWUPD_DEVICE_FLAG_BACKUP_BEFORE_INSTALL", "1099511627776"),
    ("(guint64) FWUPD_DEVICE_FLAG_CAN_EMULATION_TAG", "4503599627370496"),
    ("(guint64) FWUPD_DEVICE_FLAG_CAN_VERIFY", "33554432"),
    ("(guint64) FWUPD_DEVICE_FLAG_CAN_VERIFY_IMAGE", "67108864"),
    ("(guint64) FWUPD_DEVICE_FLAG_DUAL_IMAGE", "134217728"),
    ("(guint64) FWUPD_DEVICE_FLAG_EMULATED", "562949953421312"),
    ("(guint64) FWUPD_DEVICE_FLAG_EMULATION_TAG", "1125899906842624"),
    ("(guint64) FWUPD_DEVICE_FLAG_END_OF_LIFE", "70368744177664"),
    ("(guint64) FWUPD_DEVICE_FLAG_HAS_MULTIPLE_BRANCHES", "549755813888"),
    ("(guint64) FWUPD_DEVICE_FLAG_HISTORICAL", "4194304"),
    ("(guint64) FWUPD_DEVICE_FLAG_INSTALL_ALL_RELEASES", "2147483648"),
    ("(guint64) FWUPD_DEVICE_FLAG_INSTALL_SKIP_VERSION_CHECK", "9007199254740992"),
    ("(guint64) FWUPD_DEVICE_FLAG_INTERNAL", "1"),
    ("(guint64) FWUPD_DEVICE_FLAG_IS_BOOTLOADER", "8192"),
    ("(guint64) FWUPD_DEVICE_FLAG_LOCKED", "16"),
    ("(guint64) FWUPD_DEVICE_FLAG_NEEDS_ACTIVATION", "1048576"),
    ("(guint64) FWUPD_DEVICE_FLAG_NEEDS_BOOTLOADER", "64"),
    ("(guint64) FWUPD_DEVICE_FLAG_NEEDS_REBOOT", "256"),
    ("(guint64) FWUPD_DEVICE_FLAG_NEEDS_SHUTDOWN", "131072"),
    ("(guint64) FWUPD_DEVICE_FLAG_NONE", "0"),
    ("(guint64) FWUPD_DEVICE_FLAG_NOTIFIED", "1024"),
    ("(guint64) FWUPD_DEVICE_FLAG_ONLY_EXPLICIT_UPDATES", "2251799813685248"),
    ("(guint64) FWUPD_DEVICE_FLAG_ONLY_VERSION_UPGRADE", "8796093022208"),
    ("(guint64) FWUPD_DEVICE_FLAG_REPORTED", "512"),
    ("(guint64) FWUPD_DEVICE_FLAG_REQUIRE_AC", "8"),
    ("(guint64) FWUPD_DEVICE_FLAG_SELF_RECOVERY", "268435456"),
    ("(guint64) FWUPD_DEVICE_FLAG_SIGNED_PAYLOAD", "140737488355328"),
    ("(guint64) FWUPD_DEVICE_FLAG_SUPPORTED", "32"),
    ("(guint64) FWUPD_DEVICE_FLAG_UNKNOWN", "18446744073709551615"),
    ("(guint64) FWUPD_DEVICE_FLAG_UNREACHABLE", "17592186044416"),
    ("(guint64) FWUPD_DEVICE_FLAG_UNSIGNED_PAYLOAD", "281474976710656"),
    ("(guint64) FWUPD_DEVICE_FLAG_UPDATABLE", "2"),
    ("(guint64) FWUPD_DEVICE_FLAG_UPDATABLE_HIDDEN", "137438953472"),
    ("(guint64) FWUPD_DEVICE_FLAG_USABLE_DURING_UPDATE", "536870912"),
    ("(guint64) FWUPD_DEVICE_FLAG_VERSION_CHECK_REQUIRED", "1073741824"),
    ("(guint64) FWUPD_DEVICE_FLAG_WAIT_FOR_REPLUG", "16384"),
    ("(guint64) FWUPD_DEVICE_FLAG_WILDCARD_INSTALL", "4398046511104"),
    ("(guint64) FWUPD_DEVICE_FLAG_WILL_DISAPPEAR", "16777216"),
    ("FWUPD_DEVICE_ID_ANY", "*"),
    ("(guint) FWUPD_DEVICE_PROBLEM_DISPLAY_REQUIRED", "2048"),
    ("(guint) FWUPD_DEVICE_PROBLEM_FIRMWARE_LOCKED", "16384"),
    ("(guint) FWUPD_DEVICE_PROBLEM_INSECURE_PLATFORM", "8192"),
    ("(guint) FWUPD_DEVICE_PROBLEM_IN_USE", "1024"),
    ("(guint) FWUPD_DEVICE_PROBLEM_IS_EMULATED", "64"),
    ("(guint) FWUPD_DEVICE_PROBLEM_LID_IS_CLOSED", "32"),
    ("(guint) FWUPD_DEVICE_PROBLEM_LOWER_PRIORITY", "4096"),
    ("(guint) FWUPD_DEVICE_PROBLEM_MISSING_LICENSE", "128"),
    ("(guint) FWUPD_DEVICE_PROBLEM_NONE", "0"),
    ("(guint) FWUPD_DEVICE_PROBLEM_POWER_TOO_LOW", "4"),
    ("(guint) FWUPD_DEVICE_PROBLEM_REQUIRE_AC_POWER", "16"),
    ("(guint) FWUPD_DEVICE_PROBLEM_SYSTEM_INHIBIT", "256"),
    ("(guint) FWUPD_DEVICE_PROBLEM_SYSTEM_POWER_TOO_LOW", "1"),
    ("(guint) FWUPD_DEVICE_PROBLEM_UNKNOWN", "4294967295"),
    ("(guint) FWUPD_DEVICE_PROBLEM_UNREACHABLE", "2"),
    ("(guint) FWUPD_DEVICE_PROBLEM_UPDATE_IN_PROGRESS", "512"),
    ("(guint) FWUPD_DEVICE_PROBLEM_UPDATE_PENDING", "8"),
    ("(gint) FWUPD_ERROR_AC_POWER_REQUIRED", "12"),
    ("(gint) FWUPD_ERROR_ALREADY_PENDING", "3"),
    ("(gint) FWUPD_ERROR_AUTH_EXPIRED", "17"),
    ("(gint) FWUPD_ERROR_AUTH_FAILED", "4"),
    ("(gint) FWUPD_ERROR_BATTERY_LEVEL_TOO_LOW", "15"),
    ("(gint) FWUPD_ERROR_BROKEN_SYSTEM", "14"),
    ("(gint) FWUPD_ERROR_BUSY", "20"),
    ("(gint) FWUPD_ERROR_INTERNAL", "0"),
    ("(gint) FWUPD_ERROR_INVALID_DATA", "18"),
    ("(gint) FWUPD_ERROR_INVALID_FILE", "7"),
    ("FWUPD_ERROR_LAST", "22"),
    ("(gint) FWUPD_ERROR_NEEDS_USER_ACTION", "16"),
    ("(gint) FWUPD_ERROR_NOTHING_TO_DO", "9"),
    ("(gint) FWUPD_ERROR_NOT_FOUND", "8"),
    ("(gint) FWUPD_ERROR_NOT_REACHABLE", "21"),
    ("(gint) FWUPD_ERROR_NOT_SUPPORTED", "10"),
    ("(gint) FWUPD_ERROR_PERMISSION_DENIED", "13"),
    ("(gint) FWUPD_ERROR_READ", "5"),
    ("(gint) FWUPD_ERROR_SIGNATURE_INVALID", "11"),
    ("(gint) FWUPD_ERROR_TIMED_OUT", "19"),
    ("(gint) FWUPD_ERROR_VERSION_NEWER", "1"),
    ("(gint) FWUPD_ERROR_VERSION_SAME", "2"),
    ("(gint) FWUPD_ERROR_WRITE", "6"),
    ("(guint) FWUPD_FEATURE_FLAG_ALLOW_AUTHENTICATION", "256"),
    ("(guint) FWUPD_FEATURE_FLAG_CAN_REPORT", "1"),
    ("(guint) FWUPD_FEATURE_FLAG_COMMUNITY_TEXT", "64"),
    ("(guint) FWUPD_FEATURE_FLAG_DETACH_ACTION", "2"),
    ("(guint) FWUPD_FEATURE_FLAG_FDE_WARNING", "32"),
    ("(guint) FWUPD_FEATURE_FLAG_NONE", "0"),
    ("(guint) FWUPD_FEATURE_FLAG_REQUESTS", "16"),
    ("(guint) FWUPD_FEATURE_FLAG_REQUESTS_NON_GENERIC", "512"),
    ("(guint) FWUPD_FEATURE_FLAG_SHOW_PROBLEMS", "128"),
    ("(guint) FWUPD_FEATURE_FLAG_SWITCH_BRANCH", "8"),
    ("(guint) FWUPD_FEATURE_FLAG_UNKNOWN", "4294967295"),
    ("(guint) FWUPD_FEATURE_FLAG_UPDATE_ACTION", "4"),
    ("(guint) FWUPD_GUID_FLAG_MIXED_ENDIAN", "2"),
    ("(guint) FWUPD_GUID_FLAG_NAMESPACE_MICROSOFT", "1"),
    ("(guint) FWUPD_GUID_FLAG_NONE", "0"),
    ("(guint) FWUPD_INSTALL_FLAG_ALLOW_BRANCH_SWITCH", "32"),
    ("(guint) FWUPD_INSTALL_FLAG_ALLOW_OLDER", "4"),
    ("(guint) FWUPD_INSTALL_FLAG_ALLOW_REINSTALL", "2"),
    ("(guint) FWUPD_INSTALL_FLAG_FORCE", "8"),
    ("(guint) FWUPD_INSTALL_FLAG_IGNORE_CHECKSUM", "64"),
    ("(guint) FWUPD_INSTALL_FLAG_IGNORE_REQUIREMENTS", "512"),
    ("(guint) FWUPD_INSTALL_FLAG_IGNORE_VID_PID", "128"),
    ("(guint) FWUPD_INSTALL_FLAG_NONE", "0"),
    ("(guint) FWUPD_INSTALL_FLAG_NO_HISTORY", "16"),
    ("(guint) FWUPD_INSTALL_FLAG_NO_SEARCH", "256"),
    ("(guint) FWUPD_INSTALL_FLAG_ONLY_EMULATED", "1024"),
    ("(guint) FWUPD_INSTALL_FLAG_UNKNOWN", "4294967295"),
    ("(guint) FWUPD_JSON_EXPORT_FLAG_INDENT", "1"),
    ("(guint) FWUPD_JSON_EXPORT_FLAG_NONE", "0"),
    ("(guint) FWUPD_JSON_EXPORT_FLAG_TRAILING_NEWLINE", "2"),
    ("(guint) FWUPD_JSON_LOAD_FLAG_NONE", "0"),
    ("(guint) FWUPD_JSON_LOAD_FLAG_STATIC_KEYS", "2"),
    ("(guint) FWUPD_JSON_LOAD_FLAG_TRUSTED", "1"),
    ("(gint) FWUPD_JSON_NODE_KIND_ARRAY", "3"),
    ("FWUPD_JSON_NODE_KIND_LAST", "5"),
    ("(gint) FWUPD_JSON_NODE_KIND_NULL", "0"),
    ("(gint) FWUPD_JSON_NODE_KIND_OBJECT", "4"),
    ("(gint) FWUPD_JSON_NODE_KIND_RAW", "1"),
    ("(gint) FWUPD_JSON_NODE_KIND_STRING", "2"),
    ("FWUPD_MAJOR_VERSION", "2"),
    ("FWUPD_MICRO_VERSION", "2"),
    ("FWUPD_MINOR_VERSION", "1"),
    ("(guint) FWUPD_PLUGIN_FLAG_AUTH_REQUIRED", "4096"),
    ("(guint) FWUPD_PLUGIN_FLAG_CAPSULES_UNSUPPORTED", "16"),
    ("(guint) FWUPD_PLUGIN_FLAG_CLEAR_UPDATABLE", "4"),
    ("(guint) FWUPD_PLUGIN_FLAG_DISABLED", "1"),
    ("(guint) FWUPD_PLUGIN_FLAG_EFIVAR_NOT_MOUNTED", "64"),
    ("(guint) FWUPD_PLUGIN_FLAG_ESP_NOT_FOUND", "128"),
    ("(guint) FWUPD_PLUGIN_FLAG_ESP_NOT_VALID", "65536"),
    ("(guint) FWUPD_PLUGIN_FLAG_FAILED_OPEN", "512"),
    ("(guint) FWUPD_PLUGIN_FLAG_KERNEL_TOO_OLD", "2048"),
    ("(guint) FWUPD_PLUGIN_FLAG_LEGACY_BIOS", "256"),
    ("(guint) FWUPD_PLUGIN_FLAG_MEASURE_SYSTEM_INTEGRITY", "32768"),
    ("(guint) FWUPD_PLUGIN_FLAG_MODULAR", "16384"),
    ("(guint) FWUPD_PLUGIN_FLAG_MUTABLE_ENUMERATION", "524288"),
    ("(guint) FWUPD_PLUGIN_FLAG_NONE", "0"),
    ("(guint) FWUPD_PLUGIN_FLAG_NO_HARDWARE", "8"),
    ("(guint) FWUPD_PLUGIN_FLAG_READY", "131072"),
    ("(guint) FWUPD_PLUGIN_FLAG_REQUIRE_HWID", "1024"),
    ("(guint) FWUPD_PLUGIN_FLAG_SECURE_CONFIG", "8192"),
    ("(guint) FWUPD_PLUGIN_FLAG_TEST_ONLY", "262144"),
    ("(guint) FWUPD_PLUGIN_FLAG_UNKNOWN", "4294967295"),
    ("(guint) FWUPD_PLUGIN_FLAG_UNLOCK_REQUIRED", "32"),
    ("(guint) FWUPD_PLUGIN_FLAG_USER_WARNING", "2"),
    ("(guint) FWUPD_RELEASE_FLAG_BLOCKED_APPROVAL", "32"),
    ("(guint) FWUPD_RELEASE_FLAG_BLOCKED_VERSION", "16"),
    ("(guint) FWUPD_RELEASE_FLAG_IS_ALTERNATE_BRANCH", "64"),
    ("(guint) FWUPD_RELEASE_FLAG_IS_COMMUNITY", "128"),
    ("(guint) FWUPD_RELEASE_FLAG_IS_DOWNGRADE", "8"),
    ("(guint) FWUPD_RELEASE_FLAG_IS_UPGRADE", "4"),
    ("(guint) FWUPD_RELEASE_FLAG_NONE", "0"),
    ("(guint) FWUPD_RELEASE_FLAG_TRUSTED_METADATA", "2"),
    ("(guint) FWUPD_RELEASE_FLAG_TRUSTED_PAYLOAD", "1"),
    ("(guint) FWUPD_RELEASE_FLAG_TRUSTED_REPORT", "256"),
    ("(guint) FWUPD_RELEASE_FLAG_UNKNOWN", "4294967295"),
    ("(gint) FWUPD_RELEASE_URGENCY_CRITICAL", "4"),
    ("(gint) FWUPD_RELEASE_URGENCY_HIGH", "3"),
    ("FWUPD_RELEASE_URGENCY_LAST", "5"),
    ("(gint) FWUPD_RELEASE_URGENCY_LOW", "1"),
    ("(gint) FWUPD_RELEASE_URGENCY_MEDIUM", "2"),
    ("(gint) FWUPD_RELEASE_URGENCY_UNKNOWN", "0"),
    ("(guint) FWUPD_REMOTE_FLAG_ALLOW_P2P_FIRMWARE", "32"),
    ("(guint) FWUPD_REMOTE_FLAG_ALLOW_P2P_METADATA", "16"),
    ("(guint) FWUPD_REMOTE_FLAG_APPROVAL_REQUIRED", "2"),
    ("(guint) FWUPD_REMOTE_FLAG_AUTOMATIC_REPORTS", "4"),
    ("(guint) FWUPD_REMOTE_FLAG_AUTOMATIC_SECURITY_REPORTS", "8"),
    ("(guint) FWUPD_REMOTE_FLAG_ENABLED", "1"),
    ("(guint) FWUPD_REMOTE_FLAG_NONE", "0"),
    ("(guint) FWUPD_REMOTE_FLAG_NO_PHASED_UPDATES", "64"),
    ("(gint) FWUPD_REMOTE_KIND_DIRECTORY", "3"),
    ("(gint) FWUPD_REMOTE_KIND_DOWNLOAD", "1"),
    ("FWUPD_REMOTE_KIND_LAST", "4"),
    ("(gint) FWUPD_REMOTE_KIND_LOCAL", "2"),
    ("(gint) FWUPD_REMOTE_KIND_UNKNOWN", "0"),
    ("(guint) FWUPD_REPORT_FLAG_FROM_OEM", "1"),
    ("(guint) FWUPD_REPORT_FLAG_IS_UPGRADE", "2"),
    ("(guint) FWUPD_REPORT_FLAG_NONE", "0"),
    ("(guint) FWUPD_REPORT_FLAG_UNKNOWN", "4294967295"),
    ("(guint) FWUPD_REQUEST_FLAG_ALLOW_GENERIC_IMAGE", "2"),
    ("(guint) FWUPD_REQUEST_FLAG_ALLOW_GENERIC_MESSAGE", "1"),
    ("(guint) FWUPD_REQUEST_FLAG_NONE", "0"),
    ("(guint) FWUPD_REQUEST_FLAG_NON_GENERIC_IMAGE", "8"),
    ("(guint) FWUPD_REQUEST_FLAG_NON_GENERIC_MESSAGE", "4"),
    ("(guint) FWUPD_REQUEST_FLAG_UNKNOWN", "4294967295"),
    ("FWUPD_REQUEST_ID_DO_NOT_POWER_OFF", "org.freedesktop.fwupd.request.do-not-power-off"),
    ("FWUPD_REQUEST_ID_INSERT_USB_CABLE", "org.freedesktop.fwupd.request.insert-usb-cable"),
    ("FWUPD_REQUEST_ID_PRESS_UNLOCK", "org.freedesktop.fwupd.request.press-unlock"),
    ("FWUPD_REQUEST_ID_REMOVE_REPLUG", "org.freedesktop.fwupd.request.remove-replug"),
    ("FWUPD_REQUEST_ID_REMOVE_USB_CABLE", "org.freedesktop.fwupd.request.remove-usb-cable"),
    ("FWUPD_REQUEST_ID_REPLUG_INSTALL", "org.freedesktop.fwupd.replug-install"),
    ("FWUPD_REQUEST_ID_REPLUG_POWER", "org.freedesktop.fwupd.replug-power"),
    ("FWUPD_REQUEST_ID_RESTART_DAEMON", "org.freedesktop.fwupd.restart-daemon"),
    ("(gint) FWUPD_REQUEST_KIND_IMMEDIATE", "2"),
    ("FWUPD_REQUEST_KIND_LAST", "3"),
    ("(gint) FWUPD_REQUEST_KIND_POST", "1"),
    ("(gint) FWUPD_REQUEST_KIND_UNKNOWN", "0"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_ACTION_CONFIG_FW", "4096"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_ACTION_CONFIG_OS", "8192"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_ACTION_CONTACT_OEM", "2048"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_CAN_FIX", "16384"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_CAN_UNDO", "32768"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_MISSING_DATA", "4"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_NONE", "0"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_OBSOLETED", "2"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_RUNTIME_ATTESTATION", "512"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_RUNTIME_ISSUE", "1024"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_RUNTIME_UPDATES", "256"),
    ("(guint) FWUPD_SECURITY_ATTR_FLAG_SUCCESS", "1"),
    ("(gint) FWUPD_SECURITY_ATTR_LEVEL_CRITICAL", "1"),
    ("(gint) FWUPD_SECURITY_ATTR_LEVEL_IMPORTANT", "2"),
    ("FWUPD_SECURITY_ATTR_LEVEL_LAST", "6"),
    ("(gint) FWUPD_SECURITY_ATTR_LEVEL_NONE", "0"),
    ("(gint) FWUPD_SECURITY_ATTR_LEVEL_SYSTEM_ATTESTATION", "5"),
    ("(gint) FWUPD_SECURITY_ATTR_LEVEL_SYSTEM_PROTECTION", "4"),
    ("(gint) FWUPD_SECURITY_ATTR_LEVEL_THEORETICAL", "3"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_ENABLED", "1"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_ENCRYPTED", "7"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_FOUND", "11"),
    ("FWUPD_SECURITY_ATTR_RESULT_LAST", "15"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_LOCKED", "5"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_NOT_ENABLED", "2"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_NOT_ENCRYPTED", "8"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_NOT_FOUND", "12"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_NOT_LOCKED", "6"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_NOT_SUPPORTED", "14"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_NOT_TAINTED", "10"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_NOT_VALID", "4"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_SUPPORTED", "13"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_TAINTED", "9"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_UNKNOWN", "0"),
    ("(gint) FWUPD_SECURITY_ATTR_RESULT_VALID", "3"),
    ("(guint) FWUPD_SELF_SIGN_FLAG_ADD_CERT", "2"),
    ("(guint) FWUPD_SELF_SIGN_FLAG_ADD_TIMESTAMP", "1"),
    ("(guint) FWUPD_SELF_SIGN_FLAG_NONE", "0"),
    ("(guint) FWUPD_SELF_SIGN_FLAG_UNKNOWN", "4294967295"),
    ("(gint) FWUPD_STATUS_DECOMPRESSING", "3"),
    ("(gint) FWUPD_STATUS_DEVICE_BUSY", "12"),
    ("(gint) FWUPD_STATUS_DEVICE_ERASE", "10"),
    ("(gint) FWUPD_STATUS_DEVICE_READ", "9"),
    ("(gint) FWUPD_STATUS_DEVICE_RESTART", "4"),
    ("(gint) FWUPD_STATUS_DEVICE_VERIFY", "6"),
    ("(gint) FWUPD_STATUS_DEVICE_WRITE", "5"),
    ("(gint) FWUPD_STATUS_DOWNLOADING", "8"),
    ("(gint) FWUPD_STATUS_IDLE", "1"),
    ("FWUPD_STATUS_LAST", "15"),
    ("(gint) FWUPD_STATUS_LOADING", "2"),
    ("(gint) FWUPD_STATUS_SCHEDULING", "7"),
    ("(gint) FWUPD_STATUS_SHUTDOWN", "13"),
    ("(gint) FWUPD_STATUS_UNKNOWN", "0"),
    ("(gint) FWUPD_STATUS_WAITING_FOR_AUTH", "11"),
    ("(gint) FWUPD_STATUS_WAITING_FOR_USER", "14"),
    ("(gint) FWUPD_UPDATE_STATE_FAILED", "3"),
    ("(gint) FWUPD_UPDATE_STATE_FAILED_TRANSIENT", "5"),
    ("FWUPD_UPDATE_STATE_LAST", "6"),
    ("(gint) FWUPD_UPDATE_STATE_NEEDS_REBOOT", "4"),
    ("(gint) FWUPD_UPDATE_STATE_PENDING", "1"),
    ("(gint) FWUPD_UPDATE_STATE_SUCCESS", "2"),
    ("(gint) FWUPD_UPDATE_STATE_UNKNOWN", "0"),
    ("(gint) FWUPD_VERSION_FORMAT_BCD", "6"),
    ("(gint) FWUPD_VERSION_FORMAT_DELL_BIOS", "11"),
    ("(gint) FWUPD_VERSION_FORMAT_DELL_BIOS_MSB", "13"),
    ("(gint) FWUPD_VERSION_FORMAT_HEX", "12"),
    ("(gint) FWUPD_VERSION_FORMAT_INTEL_CSME19", "14"),
    ("(gint) FWUPD_VERSION_FORMAT_INTEL_ME", "7"),
    ("(gint) FWUPD_VERSION_FORMAT_INTEL_ME2", "8"),
    ("FWUPD_VERSION_FORMAT_LAST", "15"),
    ("(gint) FWUPD_VERSION_FORMAT_NUMBER", "2"),
    ("(gint) FWUPD_VERSION_FORMAT_PAIR", "3"),
    ("(gint) FWUPD_VERSION_FORMAT_PLAIN", "1"),
    ("(gint) FWUPD_VERSION_FORMAT_QUAD", "5"),
    ("(gint) FWUPD_VERSION_FORMAT_SURFACE", "10"),
    ("(gint) FWUPD_VERSION_FORMAT_SURFACE_LEGACY", "9"),
    ("(gint) FWUPD_VERSION_FORMAT_TRIPLET", "4"),
    ("(gint) FWUPD_VERSION_FORMAT_UNKNOWN", "0"),
];


