// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from build/libfwupd
// from build/libfwupdplugin
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "FwupdBiosSetting", sizeof(FwupdBiosSetting), alignof(FwupdBiosSetting));
    printf("%s;%zu;%zu\n", "FwupdBiosSettingClass", sizeof(FwupdBiosSettingClass), alignof(FwupdBiosSettingClass));
    printf("%s;%zu;%zu\n", "FwupdBiosSettingKind", sizeof(FwupdBiosSettingKind), alignof(FwupdBiosSettingKind));
    printf("%s;%zu;%zu\n", "FwupdClient", sizeof(FwupdClient), alignof(FwupdClient));
    printf("%s;%zu;%zu\n", "FwupdClientClass", sizeof(FwupdClientClass), alignof(FwupdClientClass));
    printf("%s;%zu;%zu\n", "FwupdClientDownloadFlags", sizeof(FwupdClientDownloadFlags), alignof(FwupdClientDownloadFlags));
    printf("%s;%zu;%zu\n", "FwupdClientUploadFlags", sizeof(FwupdClientUploadFlags), alignof(FwupdClientUploadFlags));
    printf("%s;%zu;%zu\n", "FwupdCodecFlags", sizeof(FwupdCodecFlags), alignof(FwupdCodecFlags));
    printf("%s;%zu;%zu\n", "FwupdCodecInterface", sizeof(FwupdCodecInterface), alignof(FwupdCodecInterface));
    printf("%s;%zu;%zu\n", "FwupdDevice", sizeof(FwupdDevice), alignof(FwupdDevice));
    printf("%s;%zu;%zu\n", "FwupdDeviceClass", sizeof(FwupdDeviceClass), alignof(FwupdDeviceClass));
    printf("%s;%zu;%zu\n", "FwupdDeviceFlags", sizeof(FwupdDeviceFlags), alignof(FwupdDeviceFlags));
    printf("%s;%zu;%zu\n", "FwupdDeviceProblem", sizeof(FwupdDeviceProblem), alignof(FwupdDeviceProblem));
    printf("%s;%zu;%zu\n", "FwupdError", sizeof(FwupdError), alignof(FwupdError));
    printf("%s;%zu;%zu\n", "FwupdFeatureFlags", sizeof(FwupdFeatureFlags), alignof(FwupdFeatureFlags));
    printf("%s;%zu;%zu\n", "FwupdGuidFlags", sizeof(FwupdGuidFlags), alignof(FwupdGuidFlags));
    printf("%s;%zu;%zu\n", "FwupdInstallFlags", sizeof(FwupdInstallFlags), alignof(FwupdInstallFlags));
    printf("%s;%zu;%zu\n", "FwupdJsonExportFlags", sizeof(FwupdJsonExportFlags), alignof(FwupdJsonExportFlags));
    printf("%s;%zu;%zu\n", "FwupdJsonLoadFlags", sizeof(FwupdJsonLoadFlags), alignof(FwupdJsonLoadFlags));
    printf("%s;%zu;%zu\n", "FwupdJsonNodeKind", sizeof(FwupdJsonNodeKind), alignof(FwupdJsonNodeKind));
    printf("%s;%zu;%zu\n", "FwupdJsonParserClass", sizeof(FwupdJsonParserClass), alignof(FwupdJsonParserClass));
    printf("%s;%zu;%zu\n", "FwupdPlugin", sizeof(FwupdPlugin), alignof(FwupdPlugin));
    printf("%s;%zu;%zu\n", "FwupdPluginClass", sizeof(FwupdPluginClass), alignof(FwupdPluginClass));
    printf("%s;%zu;%zu\n", "FwupdPluginFlags", sizeof(FwupdPluginFlags), alignof(FwupdPluginFlags));
    printf("%s;%zu;%zu\n", "FwupdRelease", sizeof(FwupdRelease), alignof(FwupdRelease));
    printf("%s;%zu;%zu\n", "FwupdReleaseClass", sizeof(FwupdReleaseClass), alignof(FwupdReleaseClass));
    printf("%s;%zu;%zu\n", "FwupdReleaseFlags", sizeof(FwupdReleaseFlags), alignof(FwupdReleaseFlags));
    printf("%s;%zu;%zu\n", "FwupdReleaseUrgency", sizeof(FwupdReleaseUrgency), alignof(FwupdReleaseUrgency));
    printf("%s;%zu;%zu\n", "FwupdRemote", sizeof(FwupdRemote), alignof(FwupdRemote));
    printf("%s;%zu;%zu\n", "FwupdRemoteClass", sizeof(FwupdRemoteClass), alignof(FwupdRemoteClass));
    printf("%s;%zu;%zu\n", "FwupdRemoteFlags", sizeof(FwupdRemoteFlags), alignof(FwupdRemoteFlags));
    printf("%s;%zu;%zu\n", "FwupdRemoteKind", sizeof(FwupdRemoteKind), alignof(FwupdRemoteKind));
    printf("%s;%zu;%zu\n", "FwupdReport", sizeof(FwupdReport), alignof(FwupdReport));
    printf("%s;%zu;%zu\n", "FwupdReportClass", sizeof(FwupdReportClass), alignof(FwupdReportClass));
    printf("%s;%zu;%zu\n", "FwupdReportFlags", sizeof(FwupdReportFlags), alignof(FwupdReportFlags));
    printf("%s;%zu;%zu\n", "FwupdRequest", sizeof(FwupdRequest), alignof(FwupdRequest));
    printf("%s;%zu;%zu\n", "FwupdRequestClass", sizeof(FwupdRequestClass), alignof(FwupdRequestClass));
    printf("%s;%zu;%zu\n", "FwupdRequestFlags", sizeof(FwupdRequestFlags), alignof(FwupdRequestFlags));
    printf("%s;%zu;%zu\n", "FwupdRequestKind", sizeof(FwupdRequestKind), alignof(FwupdRequestKind));
    printf("%s;%zu;%zu\n", "FwupdSecurityAttr", sizeof(FwupdSecurityAttr), alignof(FwupdSecurityAttr));
    printf("%s;%zu;%zu\n", "FwupdSecurityAttrClass", sizeof(FwupdSecurityAttrClass), alignof(FwupdSecurityAttrClass));
    printf("%s;%zu;%zu\n", "FwupdSecurityAttrFlags", sizeof(FwupdSecurityAttrFlags), alignof(FwupdSecurityAttrFlags));
    printf("%s;%zu;%zu\n", "FwupdSecurityAttrLevel", sizeof(FwupdSecurityAttrLevel), alignof(FwupdSecurityAttrLevel));
    printf("%s;%zu;%zu\n", "FwupdSecurityAttrResult", sizeof(FwupdSecurityAttrResult), alignof(FwupdSecurityAttrResult));
    printf("%s;%zu;%zu\n", "FwupdSelfSignFlags", sizeof(FwupdSelfSignFlags), alignof(FwupdSelfSignFlags));
    printf("%s;%zu;%zu\n", "FwupdStatus", sizeof(FwupdStatus), alignof(FwupdStatus));
    printf("%s;%zu;%zu\n", "FwupdUpdateState", sizeof(FwupdUpdateState), alignof(FwupdUpdateState));
    printf("%s;%zu;%zu\n", "FwupdVersionFormat", sizeof(FwupdVersionFormat), alignof(FwupdVersionFormat));
    printf("%s;%zu;%zu\n", "fwupd_guid_t", sizeof(fwupd_guid_t), alignof(fwupd_guid_t));
    return 0;
}
