[constants]
ndk_path = '/opt/android/android-ndk-r27d/'
toolchain = ndk_path / 'toolchains/llvm/prebuilt/linux-x86_64'
toolchain_bin = toolchain / 'bin'
target_triple = 'x86_64-linux-android35'
rust_target_triple = 'x86_64-linux-android'
ndk_lib_path = toolchain / 'sysroot/usr/lib/x86_64-linux-android/35'

[host_machine]
system = 'android'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
sys_root = toolchain / 'sysroot'
pkg_config_libdir = ndk_lib_path
android_ndk_sysroot_arch = 'x86_64-linux-android'

[binaries]
c =     toolchain_bin / target_triple + '-clang'
cpp =   toolchain_bin / target_triple + '-clang++'
ar =    toolchain_bin / 'llvm-ar'
strip = toolchain_bin / 'llvm-strip'
rust =  ['rustc', '--target', rust_target_triple, '-C', 'linker=' + toolchain_bin / target_triple + '-clang']

[built-in options]
c_std = 'gnu11'
c_link_args = ['-Wl,-z,max-page-size=16384']
cpp_link_args = ['-Wl,-z,max-page-size=16384']
force_fallback_for = ['openssl', 'liblzma']

[project options]
tests = false
introspection = 'disabled'
passim = 'disabled'
docs = 'disabled'
binder = 'enabled'
udev_hotplug = false
openssl = 'enabled'
gnutls = 'disabled'

[libxmlb:project options]
introspection = false
gtkdoc = false
lzma = 'enabled'

[libusb:project options]
udev = 'disabled'
#debug-logging = true
android-os = true

[curl:project options]
tests = 'disabled'
