[constants]
ndk_path = '/opt/android/android-ndk-r27/'
toolchain = ndk_path / 'toolchains/llvm/prebuilt/linux-x86_64'
toolchain_bin = toolchain / 'bin'
target_triple = 'aarch64-linux-android35'
ndk_lib_path = toolchain / 'sysroot/usr/lib/aarch64-linux-android/35'

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[properties]
sys_root = toolchain / 'sysroot'
pkg_config_libdir = ndk_lib_path
android_ndk_sysroot_arch = 'aarch64-linux-android'

[binaries]
c =     toolchain_bin / target_triple + '-clang'
cpp =   toolchain_bin / target_triple + '-clang++'
ar =    toolchain_bin / 'llvm-ar'
strip = toolchain_bin / 'llvm-strip'

[built-in options]
c_std = 'gnu11'
c_link_args = ['-Wl,-z,max-page-size=16384']
cpp_link_args = ['-Wl,-z,max-page-size=16384']
force_fallback_for = ['openssl', 'xz']

[project options]
tests = false
introspection = 'disabled'
docs = 'disabled'
binder = 'enabled'
udev_hotplug = false
openssl = 'enabled'
gnutls = 'disabled'

[libxmlb:project options]
introspection = false
gtkdoc = false
lzma = 'enabled'

[libjcat:project options]
introspection=false
openssl_pkcs7=true
gnutls_pkcs7=false
gnutls_ed25519=false
gpg=false

[libusb:project options]
udev = 'disabled'
#debug-logging = true
android-os = true