[constants]
ndk_path = '/opt/android/android-ndk-r27/'
toolchain = ndk_path / 'toolchains/llvm/prebuilt/linux-x86_64'
toolchain_bin = toolchain / 'bin'
target_triple = 'aarch64-linux-android35'
rust_target_triple = 'aarch64-linux-android'
ndk_lib_path = toolchain / 'sysroot/usr/lib/aarch64-linux-android/35'

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[properties]
sys_root = toolchain / 'sysroot'
pkg_config_libdir = ndk_lib_path
android_ndk_sysroot_arch = 'aarch64-linux-android'
have_c99_vsnprintf = true
have_c99_snprintf = true
have_unix98_printf = true
va_val_copy = true
growing_stack = false
have_proc_self_cmdline = true

[binaries]
c =     toolchain_bin / target_triple + '-clang'
cpp =   toolchain_bin / target_triple + '-clang++'
ar =    toolchain_bin / 'llvm-ar'
strip = toolchain_bin / 'llvm-strip'
rust =  ['rustc', '--target', rust_target_triple]
rust_ld = toolchain_bin / target_triple + '-clang'

[built-in options]
c_std = 'gnu11'
default_library = 'static'
c_link_args = ['-Wl,-z,max-page-size=16384']
cpp_link_args = ['-Wl,-z,max-page-size=16384']
force_fallback_for = ['openssl', 'liblzma']

[project options]
tests = false
introspection = 'disabled'
passim = 'disabled'
docs = 'disabled'
build = 'binder'
udev_hotplug = false
openssl = 'enabled'
gnutls = 'disabled'

[libxmlb:project options]
introspection = false
gtkdoc = false
lzma = 'enabled'

[glib:project options]
tests = false

[libjcat:project options]
introspection=false
openssl_pkcs7=true
gnutls_pkcs7=false
gnutls_ed25519=false
gpg=false

[libusb:project options]
udev = 'disabled'
#debug-logging = true
android-os = true

[curl:project options]
tests = 'disabled'
