#These are in a generic looking directory because
#that is where gnome-desktop-testing expects to
#find them. for more information see:
#https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872458
usr/share/installed-tests/*
usr/lib/*/fwupd-plugins-3/libfu_plugin_test.so
usr/lib/*/fwupd-plugins-3/libfu_plugin_invalid.so
debian/lintian/fwupd-tests usr/share/lintian/overrides
etc/fwupd/remotes.d/fwupd-tests.conf
