usr/bin/dfu-tool
usr/bin/fwupdmgr
etc/*
usr/share/bash-completion
usr/share/fwupd/*
usr/share/dbus-1/*
usr/share/polkit-1/*
usr/share/locale
usr/share/metainfo/*
usr/lib/*/fwupd
usr/lib/*/fwupdtool
usr/share/man/man1/*
lib/systemd/system/*
var/lib/fwupd
lib/udev/rules.d/*
data/daemon.conf etc/fwupd
debian/fwupd.pkla /var/lib/polkit-1/localauthority/10-vendor.d
usr/lib/*/fwupd-plugins-*/*.so
debian/lintian/fwupd usr/share/lintian/overrides
