#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = purge ]; then
	rm -rf /var/lib/fwupd/gnupg
	rm -f /var/cache/app-info/xmls/fwupd.xml
fi

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
	dpkg-maintscript-helper rm_conffile \
		/etc/fwupd.conf 1.0.0~ -- "$@"
	dpkg-maintscript-helper rm_conffile \
		/etc/fwupd/remotes.d/fwupd.conf 1.2.7~ -- "$@"
	dpkg-maintscript-helper rm_conffile \
		/etc/dbus-1/system.d/org.freedesktop.fwupd.conf 1.3.2~ -- "$@"
fi
