#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = purge ]; then
	rm -rf /var/lib/fwupd /var/cache/fwupd /var/cache/fwupdmgr
	rm -f /var/cache/app-info/xmls/fwupd.xml
fi

#Perform transition from /etc/fwupd/uefi.conf to /etc/fwupd/uefi_capsule.conf
if dpkg-maintscript-helper supports mv_conffile 2>/dev/null; then
	ORIGINAL=/etc/fwupd/uefi.conf
	NEW=/etc/fwupd/uefi_capsule.conf
	dpkg-maintscript-helper mv_conffile $ORIGINAL $NEW 1.5.5~ -- "$@"
fi
