#!/bin/sh
set -e

#DEBHELPER#

if [ "$1" = remove -o "$1" = purge ]; then
	if [ -f /etc/fwupd/fwupd.conf ]; then
		if [ "$CI" = "true" ]; then
			fwupdtool modify-config DisabledPlugins "test;test_ble"
			fwupdtool modify-config AllowEmulation false
		else
			echo "To disable test suite, modify /etc/fwupd/fwupd.conf"
		fi
	fi
	if [ -f /etc/fwupd/remotes.d/fwupd-tests.conf ]; then
		if [ "$CI" = "true" ]; then
			sed "s,^Enabled=true,Enabled=false," -i /etc/fwupd/remotes.d/fwupd-tests.conf
		else
			echo "To enable test suite, enable fwupd-tests remote"
		fi
	fi
fi
