#!/usr/bin/env bash
# Setup the repository and local system for development

set -e

cd "$(dirname "$0")/.."

HELPER=./contrib/ci/fwupd_setup_helpers.py
HELPER_ARGS=""
INSTALL_BUILD_DEPS="n"
SETUP_PRE_PUSH="n"

howto() {
    echo ""
    echo "To enter fwupd development environment run:"
    echo ""
    echo "# source venv/bin/activate"
    echo ""
}

instructions() {
    cat <<'EOF'
echo "To build or rebuild fwupd within development environment run:"
echo ""
echo "# build-fwupd"
echo ""
echo "To run the test suite run:"
echo ""
echo "# test-fwupd"
echo ""
echo "To run any tool under gdbserver add DEBUG=1 to env, for example:"
echo ""
echo "# DEBUG=1 fwupdtool get-devices"
echo ""
echo "To leave fwupd development environment run:"
echo ""
echo "# deactivate"
EOF
}

usage() {
    echo "Usage: $(basename "$0") [OPTIONS]"
    echo ""
    echo "Set up the fwupd build"
    echo ""
    echo "OPTIONS:"
    echo "  --debug                   ... enable debugging output"
    echo "  --help                    ... print this help"
    echo "  --os=[fedora|ubuntu|...]  ... the operating system to set up the build for."
    echo ""
    echo "Once set up, the following commands become available:"
    howto
    instructions | bash
}

setup_deps() {
    if [ "$INSTALL_BUILD_DEPS" = "y" ]; then
        case $OS in
        debian | ubuntu | arch | fedora | darwin | freebsd)
            # shellcheck disable=SC2086
            python3 "$HELPER" install-dependencies $HELPER_ARGS -y
            ;;
        nixos)
            echo "NixOS detected, using nix-shell for build dependencies"
            ;;
        esac
    fi
}

setup_run_wrappers() {
    BASE=../../contrib/
    BIN=venv/bin/
    TEMPLATE="${BASE}/launch-venv.sh"
    # launch wrappers
    for F in fwupdtool fwupdmgr fwupd; do
        ln -sf "$TEMPLATE" "${BIN}/${F}"
    done
    # build wrapper
    ln -sf "${BASE}/build-venv.sh" "${BIN}/build-fwupd"
    ln -sf "${BASE}/test-venv.sh" "${BIN}/test-fwupd"
}

setup_vscode() {
    # Add default vscode settings and debug launcher
    SOURCED=./contrib/vscode
    TARGETD=./.vscode
    SETTINGS_F=settings.json
    LAUNCH_F=launch.json
    TASK_F=tasks.json
    for f in $SETTINGS_F $LAUNCH_F $TASK_F; do
        TEMPLATE="${SOURCED}/${f}"
        TARGETF="${TARGETD}/${f}"
        mkdir -p "${TARGETD}"
        echo "Copy ${TEMPLATE} to ${TARGETF}."
        cp "${TEMPLATE}" "${TARGETF}"
    done
}

setup_git() {
    if [ -z "$CI" ]; then
        echo "Configuring git environment"
        git config include.path ../.gitconfig
    fi
}

install_pip() {
    package=$1
    if ! python3 -m pip install "$package"; then
        # shellcheck disable=SC2086
        python3 "$HELPER" install-pip $HELPER_ARGS -y
    fi
    #try once more
    python3 -m pip install "$package"
}

setup_virtualenv() {
    VENV="${PWD}/venv"
    echo "Setting up virtualenv in ${VENV}"
    if [ "$OS" = "nixos" ]; then
        python3 -m venv "${VENV}" --prompt fwupd
        touch "${VENV}/.nixos"
    else
        if ! command -v virtualenv >/dev/null 2>&1; then
            install_pip virtualenv
        fi
        virtualenv --system-site-packages "${VENV}" --prompt fwupd
    fi
    # shellcheck disable=SC1091
    source "${VENV}/bin/activate"
    instructions >>"${VENV}/bin/activate"
    cat >>"${VENV}/bin/activate" <<EOF
if [ -n "\$BASH_VERSION" ]; then
    . data/bash-completion/fwupdtool
    . data/bash-completion/fwupdmgr
fi
export MANPATH=\${VIRTUAL_ENV}/dist/share/man:
EOF
}

setup_precommit() {
    if [ -z "$CI" ]; then
        echo "Configuring pre-commit hooks"
        install_pip pre-commit
        pre-commit install
    fi
}

setup_prepush() {
    if ! command -v pre-commit >/dev/null 2>&1; then
        return
    fi
    if [ "$SETUP_PRE_PUSH" = "y" ]; then
        pre-commit install -t pre-push
    else
        pre-commit uninstall -t pre-push
    fi
}

check_markdown() {
    python3 "$HELPER" test-markdown
}

check_jinja2() {
    python3 "$HELPER" test-jinja2
}

check_meson() {
    python3 "$HELPER" test-meson
}

detect_os() {
    if [ -z "${OS:-}" ]; then
        OS="$(python3 "$HELPER" detect-profile)"
        if [ -z "$OS" ]; then
            install_pip distro
            OS="$(python3 "$HELPER" detect-profile)"
        fi
        echo "Using OS profile $OS to setup"
    fi
    if [ -n "$OS" ]; then
        HELPER_ARGS="$HELPER_ARGS --os $OS"
    fi
    if [ -n "$DEBUG" ]; then
        HELPER_ARGS="$HELPER_ARGS --debug"
    fi
}

for i in "$@"; do
    case $i in
    --os=*)
        OS="${i#*=}"
        shift
        ;;
    --debug)
        set -x
        DEBUG=1
        shift
        ;;
    -h | --help)
        usage
        exit 0
        ;;
    *) ;;
    esac
done

#already setup
if [ -f venv/bin/build-fwupd ]; then
    echo "$0 has already been run"
    howto
    exit 0
fi

PYTHON_VERSION="$(python3 --version 2>/dev/null)"
if [ -z "$PYTHON_VERSION" ]; then
    echo "Install python3 to run this script" >&2
    exit 1
fi

#needed for arguments for some commands
detect_os

#if interactive install build deps and prepare environment
if [ -n "$CI" ]; then
    INSTALL_BUILD_DEPS="y"
    SETUP_PRE_PUSH="y"
elif [ -t 2 ]; then
    read -rp "Install build dependencies? (y/N) " INSTALL_BUILD_DEPS
    read -rp "Run tests locally before pushing to remote branches? THIS WILL SLOW DOWN EVERY PUSH but reduce the risk of failing CI. (y/N) " SETUP_PRE_PUSH
fi

setup_deps
setup_virtualenv
setup_run_wrappers
check_markdown
check_jinja2
setup_vscode
setup_git
check_meson
setup_precommit

#needs to be after pre-commit is sourced
setup_prepush

howto
