# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - enhancement
  - regression
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.
  Please note: We are just a few people who contribute to a shared project,
  and it's impossible for us to fix every bug with such limited resources.
  
  If you want to investigate and try to help solve this yourself, we will
  review all pull requests from new contributors.
  
  If this is issue is important to you for your business please talk with
  your technical account manager about arranging resources to solve this issue.
  You might even consider hiring someone to write the code if you're unable
  to do so yourself, e.g. see: https://fwupd.org/lvfs/docs/consulting

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
