extraction:
  python:
    python_setup:
      version: "3"
  cpp:
    prepare:
      packages:
      - python3-gi
      - libarchive-tools
      - libcogl-pango-dev
      - python3-pil
      - python3-cairo
      - libssl-dev
    after_prepare:
    - "wget -O libxmlb.zip https://github.com/hughsie/libxmlb/archive/0.1.13.zip"
    - "mkdir -p subprojects/libxmlb"
    - "bsdtar --strip-components=1 -xvf libxmlb.zip -C subprojects/libxmlb"
    - "wget https://download.flashrom.org/releases/flashrom-v1.2.tar.bz2"
    - "mkdir -p subprojects/flashrom"
    - "bsdtar --strip-components=1 -xvf flashrom-v1.2.tar.bz2 -C subprojects/flashrom"
    - "cd $LGTM_WORKSPACE"
    - "mkdir installdir"
    - "wget https://github.com/tpm2-software/tpm2-tss/releases/download/2.3.0/tpm2-tss-2.3.0.tar.gz"
    - "tar xf tpm2-tss-2.3.0.tar.gz"
    - "cd tpm2-tss-2.3.0"
    - "./configure --prefix=$LGTM_WORKSPACE/installdir/usr --disable-doxygen-doc"
    - "make install"
    - "export PKG_CONFIG_PATH=$LGTM_WORKSPACE/installdir/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
    - "export LD_LIBRARY_PATH=$LGTM_WORKSPACE/installdir/usr/lib:$LD_LIBRARY_PATH"
    index:
      build_command:
      - "meson setup build"
      - "ninja -C build"
