extraction:
  python:
    python_setup:
      version: "3"
  cpp:
    prepare:
      packages:
      - python3-gi
      - libarchive-tools
      - libcogl-pango-dev
      - python3-pil
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-cairo
      - python3-gi-cairo
      - libssl-dev
    after_prepare:
    - python3 -m pip install --user "meson >= 0.52.0"
    - export PATH="$HOME/.local/bin:$PATH"
    - "cd $LGTM_WORKSPACE"
    - "mkdir installdir"
    - "wget https://github.com/tpm2-software/tpm2-tss/releases/download/2.3.0/tpm2-tss-2.3.0.tar.gz"
    - "tar xf tpm2-tss-2.3.0.tar.gz"
    - "cd tpm2-tss-2.3.0"
    - "./configure --prefix=$LGTM_WORKSPACE/installdir/usr --disable-doxygen-doc"
    - "make install"
    - "export PKG_CONFIG_PATH=$LGTM_WORKSPACE/installdir/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
    - "export LD_LIBRARY_PATH=$LGTM_WORKSPACE/installdir/usr/lib:$LD_LIBRARY_PATH"
    index:
      build_command:
      - "meson setup build"
      - "ninja -C build"
