.TH "fwupdate" "1" "" @PACKAGE_VERSION@ "fwupdate man page"
.SH NAME
.PP
\f[B]fwupdate\f[R] \[em] debugging utility for UEFI firmware updates
.SH SYNOPSIS
.PP
\f[B]fwupdate\f[R] [CMD]
.SH DESCRIPTION
.PP
\f[B]fwupdate\f[R] is a deprecated tool that allows deploying capsule
updates.
.SH OPTIONS
.PP
The fwupdate command takes various options depending on the action.
Run \f[B]fwupdate \[en]help\f[R] for the full list.
.SH BUGS
.PP
See GitHub Issues: <https://github.com/fwupd/fwupd/issues>
.SH SEE ALSO
.PP
\f[B]fwupdmr(1)\f[R], \f[B]fwupdtool(1)\f[R]
