.\" Report problems in https://github.com/fwupd/fwupd
.TH man 1 "27 May 2022" @PACKAGE_VERSION@ "fwupdate man page"
.SH NAME
fwupdate \-debugging utility for UEFI firmware updates
.SH SYNOPSIS
fwupdate [CMD]
.SH DESCRIPTION
fwupdate is a deprecated tool that allows deploying capsule updates.
.SH OPTIONS
The fwupdate command takes various options depending on the action.
Run \fBfwupdate --help\fR for the full list.
.SH SEE ALSO
fwupdtool(1), fwupdmgr(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Richard Hughes (richard@hughsie.com)
