// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /home/whot/code/fwupd-rust/build/libfwupd
// from /home/whot/code/fwupd-rust/build/libfwupdplugin
// from /usr/share/gir-1.0
// DO NOT EDIT

fn main() {
    if std::env::var("DOCS_RS").is_ok() {
        // prevent linking libraries to avoid documentation failure
        return;
    }

    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        std::process::exit(1);
    }
}
