/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ble_cfg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ble_cfg.pb-c.h"
void   logi__device__proto__set_blecfg_request__init
                     (Logi__Device__Proto__SetBLECfgRequest         *message)
{
  static const Logi__Device__Proto__SetBLECfgRequest init_value = LOGI__DEVICE__PROTO__SET_BLECFG_REQUEST__INIT;
  *message = init_value;
}
size_t logi__device__proto__set_blecfg_request__get_packed_size
                     (const Logi__Device__Proto__SetBLECfgRequest *message)
{
  assert(message->base.descriptor == &logi__device__proto__set_blecfg_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logi__device__proto__set_blecfg_request__pack
                     (const Logi__Device__Proto__SetBLECfgRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logi__device__proto__set_blecfg_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logi__device__proto__set_blecfg_request__pack_to_buffer
                     (const Logi__Device__Proto__SetBLECfgRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logi__device__proto__set_blecfg_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logi__Device__Proto__SetBLECfgRequest *
       logi__device__proto__set_blecfg_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logi__Device__Proto__SetBLECfgRequest *)
     protobuf_c_message_unpack (&logi__device__proto__set_blecfg_request__descriptor,
                                allocator, len, data);
}
void   logi__device__proto__set_blecfg_request__free_unpacked
                     (Logi__Device__Proto__SetBLECfgRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logi__device__proto__set_blecfg_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logi__device__proto__set_blecfg_response__init
                     (Logi__Device__Proto__SetBLECfgResponse         *message)
{
  static const Logi__Device__Proto__SetBLECfgResponse init_value = LOGI__DEVICE__PROTO__SET_BLECFG_RESPONSE__INIT;
  *message = init_value;
}
size_t logi__device__proto__set_blecfg_response__get_packed_size
                     (const Logi__Device__Proto__SetBLECfgResponse *message)
{
  assert(message->base.descriptor == &logi__device__proto__set_blecfg_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logi__device__proto__set_blecfg_response__pack
                     (const Logi__Device__Proto__SetBLECfgResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logi__device__proto__set_blecfg_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logi__device__proto__set_blecfg_response__pack_to_buffer
                     (const Logi__Device__Proto__SetBLECfgResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logi__device__proto__set_blecfg_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logi__Device__Proto__SetBLECfgResponse *
       logi__device__proto__set_blecfg_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logi__Device__Proto__SetBLECfgResponse *)
     protobuf_c_message_unpack (&logi__device__proto__set_blecfg_response__descriptor,
                                allocator, len, data);
}
void   logi__device__proto__set_blecfg_response__free_unpacked
                     (Logi__Device__Proto__SetBLECfgResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logi__device__proto__set_blecfg_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor logi__device__proto__set_blecfg_request__field_descriptors[1] =
{
  {
    "BLE_ON",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Logi__Device__Proto__SetBLECfgRequest, ble_on),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logi__device__proto__set_blecfg_request__field_indices_by_name[] = {
  0,   /* field[0] = BLE_ON */
};
static const ProtobufCIntRange logi__device__proto__set_blecfg_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor logi__device__proto__set_blecfg_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logi.device.proto.SetBLECfgRequest",
  "SetBLECfgRequest",
  "Logi__Device__Proto__SetBLECfgRequest",
  "logi.device.proto",
  sizeof(Logi__Device__Proto__SetBLECfgRequest),
  1,
  logi__device__proto__set_blecfg_request__field_descriptors,
  logi__device__proto__set_blecfg_request__field_indices_by_name,
  1,  logi__device__proto__set_blecfg_request__number_ranges,
  (ProtobufCMessageInit) logi__device__proto__set_blecfg_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logi__device__proto__set_blecfg_response__field_descriptors[2] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Logi__Device__Proto__SetBLECfgResponse, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errors",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Logi__Device__Proto__SetBLECfgResponse, n_errors),
    offsetof(Logi__Device__Proto__SetBLECfgResponse, errors),
    &logi__device__proto__error__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logi__device__proto__set_blecfg_response__field_indices_by_name[] = {
  1,   /* field[1] = errors */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange logi__device__proto__set_blecfg_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor logi__device__proto__set_blecfg_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "logi.device.proto.SetBLECfgResponse",
  "SetBLECfgResponse",
  "Logi__Device__Proto__SetBLECfgResponse",
  "logi.device.proto",
  sizeof(Logi__Device__Proto__SetBLECfgResponse),
  2,
  logi__device__proto__set_blecfg_response__field_descriptors,
  logi__device__proto__set_blecfg_response__field_indices_by_name,
  1,  logi__device__proto__set_blecfg_response__number_ranges,
  (ProtobufCMessageInit) logi__device__proto__set_blecfg_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
