/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: device_attestation.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "device_attestation.pb-c.h"
void
logi__device__proto__get_certificate_chain_request__init(
    Logi__Device__Proto__GetCertificateChainRequest *message)
{
	static const Logi__Device__Proto__GetCertificateChainRequest init_value =
	    LOGI__DEVICE__PROTO__GET_CERTIFICATE_CHAIN_REQUEST__INIT;
	*message = init_value;
}
size_t
logi__device__proto__get_certificate_chain_request__get_packed_size(
    const Logi__Device__Proto__GetCertificateChainRequest *message)
{
	assert(message->base.descriptor ==
	       &logi__device__proto__get_certificate_chain_request__descriptor);
	return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t
logi__device__proto__get_certificate_chain_request__pack(
    const Logi__Device__Proto__GetCertificateChainRequest *message,
    uint8_t *out)
{
	assert(message->base.descriptor ==
	       &logi__device__proto__get_certificate_chain_request__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t
logi__device__proto__get_certificate_chain_request__pack_to_buffer(
    const Logi__Device__Proto__GetCertificateChainRequest *message,
    ProtobufCBuffer *buffer)
{
	assert(message->base.descriptor ==
	       &logi__device__proto__get_certificate_chain_request__descriptor);
	return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Logi__Device__Proto__GetCertificateChainRequest *
logi__device__proto__get_certificate_chain_request__unpack(ProtobufCAllocator *allocator,
							   size_t len,
							   const uint8_t *data)
{
	return (Logi__Device__Proto__GetCertificateChainRequest *)protobuf_c_message_unpack(
	    &logi__device__proto__get_certificate_chain_request__descriptor,
	    allocator,
	    len,
	    data);
}
void
logi__device__proto__get_certificate_chain_request__free_unpacked(
    Logi__Device__Proto__GetCertificateChainRequest *message,
    ProtobufCAllocator *allocator)
{
	if (!message)
		return;
	assert(message->base.descriptor ==
	       &logi__device__proto__get_certificate_chain_request__descriptor);
	protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void
logi__device__proto__get_certificate_chain_response__init(
    Logi__Device__Proto__GetCertificateChainResponse *message)
{
	static const Logi__Device__Proto__GetCertificateChainResponse init_value =
	    LOGI__DEVICE__PROTO__GET_CERTIFICATE_CHAIN_RESPONSE__INIT;
	*message = init_value;
}
size_t
logi__device__proto__get_certificate_chain_response__get_packed_size(
    const Logi__Device__Proto__GetCertificateChainResponse *message)
{
	assert(message->base.descriptor ==
	       &logi__device__proto__get_certificate_chain_response__descriptor);
	return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t
logi__device__proto__get_certificate_chain_response__pack(
    const Logi__Device__Proto__GetCertificateChainResponse *message,
    uint8_t *out)
{
	assert(message->base.descriptor ==
	       &logi__device__proto__get_certificate_chain_response__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t
logi__device__proto__get_certificate_chain_response__pack_to_buffer(
    const Logi__Device__Proto__GetCertificateChainResponse *message,
    ProtobufCBuffer *buffer)
{
	assert(message->base.descriptor ==
	       &logi__device__proto__get_certificate_chain_response__descriptor);
	return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Logi__Device__Proto__GetCertificateChainResponse *
logi__device__proto__get_certificate_chain_response__unpack(ProtobufCAllocator *allocator,
							    size_t len,
							    const uint8_t *data)
{
	return (Logi__Device__Proto__GetCertificateChainResponse *)protobuf_c_message_unpack(
	    &logi__device__proto__get_certificate_chain_response__descriptor,
	    allocator,
	    len,
	    data);
}
void
logi__device__proto__get_certificate_chain_response__free_unpacked(
    Logi__Device__Proto__GetCertificateChainResponse *message,
    ProtobufCAllocator *allocator)
{
	if (!message)
		return;
	assert(message->base.descriptor ==
	       &logi__device__proto__get_certificate_chain_response__descriptor);
	protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor
    logi__device__proto__get_certificate_chain_request__field_descriptors[2] = {
	{
	    "attestation",
	    1,
	    PROTOBUF_C_LABEL_NONE,
	    PROTOBUF_C_TYPE_STRING,
	    0, /* quantifier_offset */
	    offsetof(Logi__Device__Proto__GetCertificateChainRequest, attestation),
	    NULL,
	    &protobuf_c_empty_string,
	    0, /* flags */
	    0,
	    NULL,
	    NULL /* reserved1,reserved2, etc */
	},
	{
	    "ttl",
	    2,
	    PROTOBUF_C_LABEL_NONE,
	    PROTOBUF_C_TYPE_INT32,
	    0, /* quantifier_offset */
	    offsetof(Logi__Device__Proto__GetCertificateChainRequest, ttl),
	    NULL,
	    NULL,
	    0, /* flags */
	    0,
	    NULL,
	    NULL /* reserved1,reserved2, etc */
	},
};
static const unsigned logi__device__proto__get_certificate_chain_request__field_indices_by_name[] =
    {
	0, /* field[0] = attestation */
	1, /* field[1] = ttl */
};
static const ProtobufCIntRange
    logi__device__proto__get_certificate_chain_request__number_ranges[1 + 1] = {{1, 0}, {0, 2}};
const ProtobufCMessageDescriptor logi__device__proto__get_certificate_chain_request__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "logi.device.proto.GetCertificateChainRequest",
    "GetCertificateChainRequest",
    "Logi__Device__Proto__GetCertificateChainRequest",
    "logi.device.proto",
    sizeof(Logi__Device__Proto__GetCertificateChainRequest),
    2,
    logi__device__proto__get_certificate_chain_request__field_descriptors,
    logi__device__proto__get_certificate_chain_request__field_indices_by_name,
    1,
    logi__device__proto__get_certificate_chain_request__number_ranges,
    (ProtobufCMessageInit)logi__device__proto__get_certificate_chain_request__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    logi__device__proto__get_certificate_chain_response__field_descriptors[1] = {
	{
	    "certchain",
	    1,
	    PROTOBUF_C_LABEL_REPEATED,
	    PROTOBUF_C_TYPE_STRING,
	    offsetof(Logi__Device__Proto__GetCertificateChainResponse, n_certchain),
	    offsetof(Logi__Device__Proto__GetCertificateChainResponse, certchain),
	    NULL,
	    &protobuf_c_empty_string,
	    0, /* flags */
	    0,
	    NULL,
	    NULL /* reserved1,reserved2, etc */
	},
};
static const unsigned logi__device__proto__get_certificate_chain_response__field_indices_by_name[] =
    {
	0, /* field[0] = certchain */
};
static const ProtobufCIntRange
    logi__device__proto__get_certificate_chain_response__number_ranges[1 + 1] = {{1, 0}, {0, 1}};
const ProtobufCMessageDescriptor logi__device__proto__get_certificate_chain_response__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "logi.device.proto.GetCertificateChainResponse",
    "GetCertificateChainResponse",
    "Logi__Device__Proto__GetCertificateChainResponse",
    "logi.device.proto",
    sizeof(Logi__Device__Proto__GetCertificateChainResponse),
    1,
    logi__device__proto__get_certificate_chain_response__field_descriptors,
    logi__device__proto__get_certificate_chain_response__field_indices_by_name,
    1,
    logi__device__proto__get_certificate_chain_response__number_ranges,
    (ProtobufCMessageInit)logi__device__proto__get_certificate_chain_response__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
