/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: firmware_update.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "firmware_update.pb-c.h"
void
logi__device__proto__update_now_request__init(Logi__Device__Proto__UpdateNowRequest *message)
{
	static const Logi__Device__Proto__UpdateNowRequest init_value =
	    LOGI__DEVICE__PROTO__UPDATE_NOW_REQUEST__INIT;
	*message = init_value;
}
size_t
logi__device__proto__update_now_request__get_packed_size(
    const Logi__Device__Proto__UpdateNowRequest *message)
{
	assert(message->base.descriptor == &logi__device__proto__update_now_request__descriptor);
	return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t
logi__device__proto__update_now_request__pack(const Logi__Device__Proto__UpdateNowRequest *message,
					      uint8_t *out)
{
	assert(message->base.descriptor == &logi__device__proto__update_now_request__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t
logi__device__proto__update_now_request__pack_to_buffer(
    const Logi__Device__Proto__UpdateNowRequest *message,
    ProtobufCBuffer *buffer)
{
	assert(message->base.descriptor == &logi__device__proto__update_now_request__descriptor);
	return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Logi__Device__Proto__UpdateNowRequest *
logi__device__proto__update_now_request__unpack(ProtobufCAllocator *allocator,
						size_t len,
						const uint8_t *data)
{
	return (Logi__Device__Proto__UpdateNowRequest *)protobuf_c_message_unpack(
	    &logi__device__proto__update_now_request__descriptor,
	    allocator,
	    len,
	    data);
}
void
logi__device__proto__update_now_request__free_unpacked(
    Logi__Device__Proto__UpdateNowRequest *message,
    ProtobufCAllocator *allocator)
{
	if (!message)
		return;
	assert(message->base.descriptor == &logi__device__proto__update_now_request__descriptor);
	protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void
logi__device__proto__update_now_response__init(Logi__Device__Proto__UpdateNowResponse *message)
{
	static const Logi__Device__Proto__UpdateNowResponse init_value =
	    LOGI__DEVICE__PROTO__UPDATE_NOW_RESPONSE__INIT;
	*message = init_value;
}
size_t
logi__device__proto__update_now_response__get_packed_size(
    const Logi__Device__Proto__UpdateNowResponse *message)
{
	assert(message->base.descriptor == &logi__device__proto__update_now_response__descriptor);
	return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t
logi__device__proto__update_now_response__pack(
    const Logi__Device__Proto__UpdateNowResponse *message,
    uint8_t *out)
{
	assert(message->base.descriptor == &logi__device__proto__update_now_response__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t
logi__device__proto__update_now_response__pack_to_buffer(
    const Logi__Device__Proto__UpdateNowResponse *message,
    ProtobufCBuffer *buffer)
{
	assert(message->base.descriptor == &logi__device__proto__update_now_response__descriptor);
	return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Logi__Device__Proto__UpdateNowResponse *
logi__device__proto__update_now_response__unpack(ProtobufCAllocator *allocator,
						 size_t len,
						 const uint8_t *data)
{
	return (Logi__Device__Proto__UpdateNowResponse *)protobuf_c_message_unpack(
	    &logi__device__proto__update_now_response__descriptor,
	    allocator,
	    len,
	    data);
}
void
logi__device__proto__update_now_response__free_unpacked(
    Logi__Device__Proto__UpdateNowResponse *message,
    ProtobufCAllocator *allocator)
{
	if (!message)
		return;
	assert(message->base.descriptor == &logi__device__proto__update_now_response__descriptor);
	protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor
    logi__device__proto__update_now_request__field_descriptors[1] = {
	{
	    "reserved",
	    1,
	    PROTOBUF_C_LABEL_NONE,
	    PROTOBUF_C_TYPE_BOOL,
	    0, /* quantifier_offset */
	    offsetof(Logi__Device__Proto__UpdateNowRequest, reserved),
	    NULL,
	    NULL,
	    0, /* flags */
	    0,
	    NULL,
	    NULL /* reserved1,reserved2, etc */
	},
};
static const unsigned logi__device__proto__update_now_request__field_indices_by_name[] = {
    0, /* field[0] = reserved */
};
static const ProtobufCIntRange logi__device__proto__update_now_request__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}};
const ProtobufCMessageDescriptor logi__device__proto__update_now_request__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "logi.device.proto.UpdateNowRequest",
    "UpdateNowRequest",
    "Logi__Device__Proto__UpdateNowRequest",
    "logi.device.proto",
    sizeof(Logi__Device__Proto__UpdateNowRequest),
    1,
    logi__device__proto__update_now_request__field_descriptors,
    logi__device__proto__update_now_request__field_indices_by_name,
    1,
    logi__device__proto__update_now_request__number_ranges,
    (ProtobufCMessageInit)logi__device__proto__update_now_request__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor
    logi__device__proto__update_now_response__field_descriptors[1] = {
	{
	    "started",
	    1,
	    PROTOBUF_C_LABEL_NONE,
	    PROTOBUF_C_TYPE_BOOL,
	    0, /* quantifier_offset */
	    offsetof(Logi__Device__Proto__UpdateNowResponse, started),
	    NULL,
	    NULL,
	    0, /* flags */
	    0,
	    NULL,
	    NULL /* reserved1,reserved2, etc */
	},
};
static const unsigned logi__device__proto__update_now_response__field_indices_by_name[] = {
    0, /* field[0] = started */
};
static const ProtobufCIntRange logi__device__proto__update_now_response__number_ranges[1 + 1] = {
    {1, 0},
    {0, 1}};
const ProtobufCMessageDescriptor logi__device__proto__update_now_response__descriptor = {
    PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
    "logi.device.proto.UpdateNowResponse",
    "UpdateNowResponse",
    "Logi__Device__Proto__UpdateNowResponse",
    "logi.device.proto",
    sizeof(Logi__Device__Proto__UpdateNowResponse),
    1,
    logi__device__proto__update_now_response__field_descriptors,
    logi__device__proto__update_now_response__field_indices_by_name,
    1,
    logi__device__proto__update_now_response__number_ranges,
    (ProtobufCMessageInit)logi__device__proto__update_now_response__init,
    NULL,
    NULL,
    NULL /* reserved[123] */
};
