.\" Report problems in https://github.com/fwupd/fwupd
.TH man 8 "11 April 2021" @PACKAGE_VERSION@ "dbxtool man page"
.SH NAME
dbxtool \- modify the dbx revokation list
.SH SYNOPSIS
dbxtool [CMD]
.SH DESCRIPTION
.PP
This manual page documents briefly the \fBdbxtool\fR command.
.PP
\fBdbxtool\fR allows a user to operate on the UEFI dbx revokation list.
This tool can be used to list the current dbx contents or update it to a newer
version.
.SH OPTIONS
The dbxtool command takes various options depending on the action.
Run \fBdbxtool --help\fR for the full list.
.SH SEE ALSO
fwupdmgr(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Richard Hughes (richard@hughsie.com)
