.TH "dbxtool" "1" "" @PACKAGE_VERSION@ "dbxtool man page"
.SH NAME
.PP
\f[B]dbxtool\f[R] \[em] modify the dbx revocation list
.SH SYNOPSIS
.PP
\f[B]dbxtool\f[R] [CMD]
.SH DESCRIPTION
.PP
This manual page documents briefly the \f[B]dbxtool\f[R] command.
.PP
\f[B]dbxtool\f[R] allows a user to operate on the UEFI dbx revocation
list.
This tool can be used to list the current dbx contents or update it to a
newer version.
.SH OPTIONS
.PP
The dbxtool command takes various options depending on the action.
Run \f[B]dbxtool \[en]help\f[R] for the full list.
.SH BUGS
.PP
See GitHub Issues: <https://github.com/fwupd/fwupd/issues>
.SH SEE ALSO
.PP
fwupdtool(1), fwupdmgr(1)
