/*
 * Copyright 2015 Richard Hughes <richard@hughsie.com>
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

#pragma once

#include <glib.h>

extern GQuark FU_DFU_DEVICE_FLAG_CAN_DOWNLOAD;
extern GQuark FU_DFU_DEVICE_FLAG_CAN_UPLOAD;
extern GQuark FU_DFU_DEVICE_FLAG_MANIFEST_TOL;
extern GQuark FU_DFU_DEVICE_FLAG_WILL_DETACH;
extern GQuark FU_DFU_DEVICE_FLAG_CAN_ACCELERATE;
extern GQuark FU_DFU_DEVICE_FLAG_ATTACH_UPLOAD_DOWNLOAD;
extern GQuark FU_DFU_DEVICE_FLAG_FORCE_DFU_MODE;
extern GQuark FU_DFU_DEVICE_FLAG_IGNORE_POLLTIMEOUT;
extern GQuark FU_DFU_DEVICE_FLAG_IGNORE_RUNTIME;
extern GQuark FU_DFU_DEVICE_FLAG_IGNORE_UPLOAD;
extern GQuark FU_DFU_DEVICE_FLAG_NO_DFU_RUNTIME;
extern GQuark FU_DFU_DEVICE_FLAG_NO_GET_STATUS_UPLOAD;
extern GQuark FU_DFU_DEVICE_FLAG_NO_PID_CHANGE;
extern GQuark FU_DFU_DEVICE_FLAG_USE_ANY_INTERFACE;
extern GQuark FU_DFU_DEVICE_FLAG_USE_ATMEL_AVR;
extern GQuark FU_DFU_DEVICE_FLAG_USE_PROTOCOL_ZERO;
extern GQuark FU_DFU_DEVICE_FLAG_LEGACY_PROTOCOL;
extern GQuark FU_DFU_DEVICE_FLAG_DETACH_FOR_ATTACH;
extern GQuark FU_DFU_DEVICE_FLAG_ABSENT_SECTOR_SIZE;
extern GQuark FU_DFU_DEVICE_FLAG_MANIFEST_POLL;
extern GQuark FU_DFU_DEVICE_FLAG_NO_BUS_RESET_ATTACH;
extern GQuark FU_DFU_DEVICE_FLAG_GD32;
extern GQuark FU_DFU_DEVICE_FLAG_ALLOW_ZERO_POLLTIMEOUT;
extern GQuark FU_DFU_DEVICE_FLAG_INDEX_FORCE_DETACH;

GBytes *
fu_dfu_utils_bytes_join_array(GPtrArray *chunks);
