// Copyright 2025 Richard Hughes <richard@hughsie.com>
// SPDX-License-Identifier: LGPL-2.1-or-later

// Flags used to represent report attributes
#[derive(ToString(since=1.9.1), FromString(since=1.9.1), NoBitfield)]
enum FwupdReportFlags {
    // No report flags are set.
    // Since: 1.9.1
    None = 0,
    // Report was generated by the OEM.
    // Since: 1.9.1
    FromOem = 1 << 0,
    // New firmware was newer than the old firmware.
    // Since: 1.9.14
    IsUpgrade = 1 << 1,
    // The report flag is unknown.
    // This is usually caused by a mismatched libfwupdplugin and daemon.
    // Since: 1.9.1
    Unknown = u64::MAX,
}
