/*
 * Copyright 2024 Collabora Ltd. <colin.kinloch@collabora.com>
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

#include <gbinder.h>

enum fu_binder_calls {
	GET_DEVICES = GBINDER_FIRST_CALL_TRANSACTION,
	GET_PLUGINS,
	GET_RELEASES,
	GET_DOWNGRADES,
	GET_UPGRADES,
	GET_DETAILS,
	GET_HISTORY,
	GET_HOST_SECURITY_ATTRS,
	GET_HOST_SECURITY_EVENTS,
	GET_REPORT_METADATA,
	SET_HINTS,
	INSTALL,
	VERIFY,
	VERIFY_UPDATE,
	UNLOCK,
	ACTIVATE,
	GET_RESULTS,
	GET_REMOTES,
	GET_APPROVED_FIRMWARE,
	SET_APPROVED_FIRMWARE,
	GET_BLOCKED_FIRMWARE,
	SET_BLOCKED_FIRMWARE,
	SET_FEATURE_FLAGS,
	CLEAR_RESULTS,
	MODIFY_DEVICE,
	MODIFY_CONFIG,
	RESET_CONFIG,
	UPDATE_METADATA,
	MODIFY_REMOTE,
	FIX_HOST_SECURITY_ATTR,
	UNDO_HOST_SECURITY_ATTR,
	SELF_SIGN,
	SET_BIOS_SETTINGS,
	GET_BIOS_SETTINGS,
	INHIBIT,
	UNINHIBIT,
	QUIT,
	EMULATION_LOAD,
	EMULATION_SAVE,
};
