.\" Report problems in https://github.com/fwupd/fwupd
.TH man 8 "11 April 2021" @PACKAGE_VERSION@ "fwupdagent man page"
.SH NAME
fwupdagent \- firmware updating agent
.SH SYNOPSIS
fwupdagent [CMD]
.SH DESCRIPTION
fwupdagent used to be a command line fwupd client intended to be used by scripts.
You should now use the 100% compatible \fBfwupdmgr --json\fR command instead.
The output is JSON and guaranteed to be stable.
.SH EXIT STATUS
Commands that successfully execute will return "0".
.SH SEE ALSO
fwupdmgr(1), fwupdtool(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Richard Hughes (richard@hughsie.com)
