.TH "fwupdagent" "1" "" @PACKAGE_VERSION@ "fwupdagent man page"
.hy
.SH NAME
.PP
\f[B]fwupdagent\f[R] \[em] firmware updating agent
.SH SYNOPSIS
.PP
\f[B]fwupdagent\f[R] [CMD]
.SH DESCRIPTION
.PP
fwupdagent used to be a command line fwupd client intended to be used by
scripts.
You should now use the 100% compatible \f[B]fwupdmgr --json\f[R] command
instead.
The output is JSON and guaranteed to be stable.
.SH EXIT STATUS
.PP
Commands that successfully execute will return \[lq]0\[rq].
.SH BUGS
.PP
See GitHub Issues: <https://github.com/fwupd/fwupd/issues>
.SH SEE ALSO
.PP
fwupdmgr(1), fwupdtool(1)
