.TH "fwupdtool" "1" "" @PACKAGE_VERSION@ "fwupdtool man page"
.hy
.SH NAME
.PP
\f[B]fwupdtool\f[R] \[em] standalone firmware update utility
.SH SYNOPSIS
.PP
\f[B]fwupdtool\f[R] [CMD]
.SH DESCRIPTION
.PP
This tool allows an administrator to use fwupd plugins directly without
using the daemon process, which may be faster or easier to use when
creating or debugging specific plugins.
For most end-users, \f[B]fwupdmgr\f[R] is a more suitable program to use
in almost all cases.
.PP
Additionally \f[B]fwupdtool\f[R] can be used to convert firmware from
various different formats, or to modify the images contained inside the
container firmware file.
For example, you can convert DFU or Intel HEX firmware into the
vendor-specific format.
.SH OPTIONS
.PP
The fwupdtool command takes various options depending on the action.
Run \f[B]fwupdtool --help\f[R] for the full list.
Note that some runtimes failures can be ignored using \f[B]--force\f[R].
.SH EXIT STATUS
.PP
Commands that successfully execute will return \[lq]0\[rq], but commands
that have no actions but successfully execute will return \[lq]2\[rq].
.SH BUGS
.PP
See GitHub Issues: <https://github.com/fwupd/fwupd/issues>
.SH SEE ALSO
.PP
fwupdmgr(1)
