FROM debian:unstable

RUN apt-get update -qq
RUN apt-get install -yq --no-install-recommends \
	debhelper \
	devscripts \
	docbook-utils \
	fontconfig \
	fontconfig-config \
	fonts-dejavu \
	gcab \
	gettext \
	gir1.2-appstreamglib-1.0 \
	gir1.2-pango-1.0 \
	gobject-introspection \
	gtk-doc-tools \
	texlive-fonts-recommended \
	locales \
	libappstream-glib-dev \
	libarchive-dev \
	libcairo-dev \
	libcairo-gobject2 \
	libcolord-dev \
	libcolorhug-dev \
	libefivar-dev \
	libelf-dev \
	libfreetype6-dev \
	libfwup-dev \
	libgcab-dev \
	libgirepository1.0-dev \
	libglib2.0-dev \
	libgpgme11-dev \
	libgudev-1.0-dev \
	libgusb-dev \
	libpolkit-gobject-1-dev \
	libsmbios-dev \
	libsoup2.4-dev \
	libsqlite3-dev \
	libtool-bin \
	meson \
	pkg-config \
	policykit-1 \
	python3-gi-cairo \
	python3-pil \
	udev \
	systemd \
	valgrind
#deps needed only for installed tests
RUN apt-get install -yq --no-install-recommends \
        gnome-desktop-testing dbus-x11 ca-certificates \
        python-gi python-requests
RUN mkdir /build
WORKDIR /build
