FROM archlinux/base
# set the locale
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
# keep the package DB
RUN rm /usr/share/libalpm/hooks/package-cleanup.hook
# update the image, install devel packages
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm base-devel
# runtime deps
RUN pacman -S --noconfirm \
              appstream-glib \
              colord \
              fwupdate
# buildtime deps
RUN pacman -S --noconfirm \
              adobe-source-han-sans-cn-fonts \
              docbook-utils \
              docbook-sgml \
              gobject-introspection \
              gtk-doc \
              meson \
              perl-sgmls \
              python-cairo \
              python-gobject \
              python-pillow \
              ttf-dejavu \
              valgrind
# CI dep
RUN pacman -S --noconfirm git
# add an user to build the package with
RUN useradd -s /bin/bash build
RUN echo 'build ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
# prepare the build environment
RUN mkdir /build
RUN chown build /build
USER build
WORKDIR /build
