# -*- mode: dockerfile -*-
FROM debian:testing
ENV CI_NETWORK=true
RUN echo fubar > /etc/machine-id
RUN set -euxo pipefail; \
    export DEBIAN_FRONTEND=noninteractive; \
%%%SETUP%%% \
    apt-get update; \
    apt-get install --yes --no-install-recommends \
    build-essential \
    dpkg-dev \
    python3-apt \
%%%DEPENDENCIES%%%; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*
WORKDIR /github/workspace
