FROM debian:unstable

RUN cat /etc/apt/sources.list | sed "s/deb/deb-src/" >> /etc/apt/sources.list
RUN dpkg --add-architecture s390x
RUN apt-get update -qq
RUN apt-get install -yq --no-install-recommends \
        binutils-multiarch \
        gcab \
        gcc-multilib-s390x-linux-gnu \
        gettext \
        git \
        gnutls-bin \
        libappstream-glib-dev:s390x \
        libarchive-dev:s390x \
        libcairo-dev:s390x \
        libcairo-gobject2:s390x \
        libcolord-dev:s390x \
        libcolorhug-dev:s390x \
        libelf-dev:s390x \
        libfreetype6-dev:s390x \
        libgcab-dev:s390x \
        libgirepository1.0-dev \
        libglib2.0-dev:s390x \
        libgnutls28-dev:s390x \
        libgpgme-dev:s390x \
        libgudev-1.0-dev:s390x \
        libgusb-dev:s390x \
        libicu-dev:s390x \
        libidn2-0-dev:s390x \
        libpolkit-gobject-1-dev:s390x \
        libsoup2.4-dev:s390x \
        libsqlite3-dev:s390x \
        libxml2-dev:s390x \
        locales \
        meson \
        policykit-1 \
        python3-gi-cairo \
        python3-pil \
        qemu-user \
        systemd \
        udev
RUN mkdir /build
WORKDIR /build
