FROM fedora:30
%%%OS%%%
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN echo fubar > /etc/machine-id
RUN dnf -y update
RUN echo fubar > /etc/machine-id
%%%INSTALL_DEPENDENCIES_COMMAND%%%
RUN mkdir /build
WORKDIR /build
COPY . .
CMD ["./contrib/ci/fedora.sh"]
