FROM %%%ARCH_PREFIX%%%ubuntu:focal
%%%OS%%%
ENV CI_NETWORK true
RUN echo fubar > /etc/machine-id
%%%ARCH_SPECIFIC_COMMAND%%%
%%%INSTALL_DEPENDENCIES_COMMAND%%%
WORKDIR /github/workspace
CMD ["./contrib/ci/launchpad.sh"]
