FROM debian:testing
ENV SKIP=no-commit-to-branch
RUN apt update && apt install -yq --no-install-recommends \
        git \
        patch \
        pre-commit \
        shellcheck \
        clang-format
RUN apt install wget -yq
RUN mkdir -p /tmp/repo && \
    cd /tmp/repo && \
    git init && \
    wget https://raw.githubusercontent.com/fwupd/fwupd/main/.pre-commit-config.yaml
RUN cd /tmp/repo && pre-commit run
RUN rm -rf /tmp/repo
WORKDIR /github/workspace
CMD ["./contrib/ci/precommit.sh"]
