FROM ubuntu:20.04
%%%OS%%%
ENV CI_NETWORK true
ENV CC clang
RUN echo fubar > /etc/machine-id
%%%ARCH_SPECIFIC_COMMAND%%%
%%%INSTALL_DEPENDENCIES_COMMAND%%%
WORKDIR /github/workspace
CMD ["./contrib/ci/ubuntu.sh"]
