FROM fedora:29
%%%OS%%%
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN echo fubar > /etc/machine-id
%%%INSTALL_DEPENDENCIES_COMMAND%%%
RUN dnf --enablerepo=updates-testing -y update
WORKDIR /github/workspace
CMD ["./contrib/ci/flatpak.py"]
