# -*- mode: dockerfile -*-
FROM ubuntu:rolling
ENV CI_NETWORK=true
ENV CC=clang
RUN echo fubar > /etc/machine-id
RUN set -euxo pipefail; \
    export DEBIAN_FRONTEND=noninteractive; \
    apt-get update; \
    apt-get install --yes --no-install-recommends \
    python3-apt \
%%%DEPENDENCIES%%%; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*
WORKDIR /github/workspace
CMD ["./contrib/ci/ubuntu.sh"]
