# -*- mode: dockerfile -*-
FROM {?PLATFORM-}--platform={{PLATFORM}} {-PLATFORM?}debian:{{VERSION}}
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV CI_NETWORK=true
ENV DEBIAN_FRONTEND=noninteractive
RUN echo fubar > /etc/machine-id
RUN set -euxo pipefail; \
    sed -i 's|Types: deb|Types: deb deb-src|' /etc/apt/sources.list.d/{{DISTRO}}.sources; \
{{SETUP}} \
    apt-get update -qq; \
    apt-get dist-upgrade -qq; \
    apt-get install -qq --yes --no-install-recommends \
    dpkg-dev \
    python3-apt \
{{DEPENDENCIES}}; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*
WORKDIR /github/workspace
