name: fwupd
version-script: cat $SNAPCRAFT_STAGE/version
version: 'daily'
summary: A standalone version of fwupd to install newer firmware updates
description: |
  This is a tool that can be used to install firmware updates on devices
  not yet supported by the version of fwupd distributed with the OS.

grade: stable
confinement: classic

architectures:
  - amd64

apps:
  dfu-tool:
    command: dfu-tool.wrapper
  fwupdtool:
    command: fwupdtool.wrapper
    completer:
      share/bash-completion/completions/fwupdtool
  fwupd:
    command: fwupd.wrapper
    daemon: simple
  fwupdmgr:
    command: fwupdmgr.wrapper
    completer:
      share/bash-completion/completions/fwupdmgr

parts:
  libefivar-dev:
    plugin: make
    make-parameters:
    - prefix=/
    - libdir=/lib
    source: https://github.com/rhboot/efivar/releases/download/37/efivar-37.tar.bz2
    build-packages:
      - libpopt-dev
    prime:
     - -include
     - -bin
     - -share/man
     - -lib/pkgconfig
  #adjust the paths from libefivar
  libefivar-fixpkgconfig:
    plugin: make
    source: contrib/snap/libefivar-fixpkgconfig
    make-parameters:
      - SNAPCRAFT_STAGE=$SNAPCRAFT_STAGE
    after: [libefivar-dev]
  libsmbios:
    plugin: autotools
    source: https://github.com/dell/libsmbios/archive/v2.4.2.tar.gz
    build-packages:
      - libxml2-dev
      - pkg-config
      - autoconf
      - automake
      - libtool
      - autopoint
    prime:
      - -include/
      - -lib/pkgconfig
      - -lib/python3.5
      - -sbin/
      - -share/
      - -etc/
      - -lib/*.a
  meson:
    plugin: python
    source: https://github.com/mesonbuild/meson/releases/download/0.47.2/meson-0.47.2.tar.gz
    build-packages:
      - ninja-build
    prime:
      - -bin
      - -etc
      - -lib
      - -share
      - -usr
  gudev:
    plugin: autotools
    source: https://github.com/GNOME/libgudev/archive/232.tar.gz
    configflags:
      - --disable-umockdev
    build-packages:
      - libglib2.0-dev
      - pkg-config
      - libudev-dev
      - gtk-doc-tools
      - gnome-common
    prime:
      - -include
      - -lib/girepository-1.0
      - -lib/pkgconfig
      - -share/
  # this is for the library only, we don't care about the daemon "in-snap"
  modemmanager:
    plugin: autotools
    source: https://gitlab.freedesktop.org/mobile-broadband/ModemManager.git
    #not yet tagged
    #source-tag: 1.10.0
    after: [gudev, gettext]
    # build without these; system daemon needs them
    configflags:
      - --without-mbim
      - --without-qmi
    prime:
      - -include
      - -etc
      - -sbin
      - -bin
      - -share
      - -lib/*.*a
      - -lib/pkgconfig
      - -lib/ModemManager
      - -lib/systemd
      - -lib/udev
      - -lib/girepository-1.0
  libusb:
    plugin: autotools
    source: https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.tar.bz2
    configflags:
     - --disable-static
    prime:
      - -include/
      - -lib/pkgconfig
  gusb:
    plugin: meson
    source: https://github.com/hughsie/libgusb/archive/0.3.0.tar.gz
    meson-parameters: [--prefix=/,
                       -Dtests=false,
                       -Dvapi=false,
                       -Ddocs=false]
    build-packages:
    - libgirepository1.0-dev
    prime:
    - -bin/
    - -include
    - -share
    - -lib/*/pkgconfig
    - -lib/*/girepository-1.0
    after: [meson, libusb]
  gnu-efi:
    plugin: make
    source: http://superb-dca2.dl.sourceforge.net/project/gnu-efi/gnu-efi-3.0.5.tar.bz2
    make-parameters:
      - PREFIX=/usr
    make-install-var: INSTALLROOT
    prime:
      - -usr/include/
      - -usr/lib
  #fetch the latest version of the signed bootloader
  #this might not match our fwupdx64.efi, but it's better than nothing
  fwup-efi-signed:
    build-packages:
      - python3-apt
    plugin: make
    source: contrib/snap/fwup-efi-signed
  #needed for UEFI plugin to build UX labels
  build-introspection:
    plugin: nil
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - python3-pil
    prime:
      - -etc
      - -usr
      - -lib
      - -var
  #0.19.8.1 adds support for GETTEXTDATADIRS which is needed by meson's msgfmthelper
  gettext:
    source: https://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.8.1.tar.xz
    plugin: autotools
    build-packages:
    - bison
    - libunistring-dev
    - libxml2-dev
    configflags:
    - --prefix=/usr
    - --disable-static
    - --disable-curses
    - --disable-java
    - --enable-relocatable
    - --without-emacs
    - --without-included-glib
    - --without-included-libunistring
    - --without-included-libxml
    stage-packages:
    - libunistring0
    - libxml2
    - libgomp1
    prime:
    - -**/*.a
    - -**/*.la
    - -usr/bin
    - -usr/include
    - -usr/lib/gettext
    - -usr/share
  fwupd:
    plugin: meson
    meson-parameters: [--prefix=/,
                       -Defi-includedir=$SNAPCRAFT_STAGE/usr/include/efi,
                       -Defi-ldsdir=$SNAPCRAFT_STAGE/usr/lib,
                       -Defi-libdir=$SNAPCRAFT_STAGE/usr/lib,
                       -Dtests=false,
                       -Ddaemon=true,
                       -Dgtkdoc=false,
                       -Dintrospection=false,
                       -Dman=false,
                       -Dudevdir=$SNAPCRAFT_STAGE/lib/udev,
                       "-Dlibxmlb:gtkdoc=false",
                       "-Dlibxmlb:introspection=false",
                       -Dpkcs7=false]
    source: .
    source-type: git
    override-build: |
      snapcraftctl build
      echo $(git describe HEAD --always) > $SNAPCRAFT_STAGE/version
    build-packages:
      - bash-completion
      - gcab
      - gnutls-dev
      - libarchive-dev
      - libcairo-dev
      - libelf-dev
      - libgcab-dev
      - libglib2.0-dev
      - libgpgme11-dev
      - libjson-glib-dev
      - libpango1.0-dev
      - libpolkit-gobject-1-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - locales
      - pkg-config
      - uuid-dev
    stage-packages:
      - libgcab-1.0-0
      - libarchive13
      - libassuan0
      - liblcms2-2
      - libelf1
      - libgpgme11
      - libjson-glib-1.0-0
      - libpolkit-gobject-1-0
      - libsoup2.4-1
      - glib-networking
      - libglib2.0-bin
    prime:
      # we explicitly don't want /usr/bin/gpgconf
      # this will cause gpgme to error finding it
      # but that also avoids trying to use non-existent
      # /usr/bin/gpg2
      - -usr/bin
      - -usr/sbin
      - -usr/share/man
      - -usr/share/GConf
      - -etc/X11
      - -etc/ldap
      - -etc/logcheck
      - -usr/lib/dconf
      - -usr/lib/gcc
      - -usr/lib/glib-networking
      - -usr/lib/gnupg2
      - -usr/lib/sasl2
      - -usr/lib/systemd
      - -usr/lib/*/audit
      - -usr/share/glib-2.0/schemas
      - -usr/share/X11
      - -include
      - -lib/systemd
      - -lib/udev
      - -lib/*/pkgconfig
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/installed-tests
      - -usr/share/polkit-1
      - -usr/share/vala
      - -usr/share/doc
      - -usr/share/gnupg2
      - -usr/share/info
      - -usr/share/gir-1.0
      - -usr/share/upstart
      - -usr/lib/*/pkgconfig
    after: [gudev, gusb, gnu-efi, libefivar-fixpkgconfig, libsmbios, build-introspection, gettext, modemmanager]
  fix-bash-completion:
    plugin: make
    source: contrib/snap/fix-bash-completion
    after: [fwupd]
  update-mime:
    plugin: make
    source: contrib/snap/update-mime
    stage-packages:
      - shared-mime-info
      - gsettings-desktop-schemas
      - libxml2
    prime:
      - -usr/bin
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/man
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/GConf
    after: [fwupd]
  fwupd-wrappers:
    plugin: dump
    source: contrib/snap
    stage:
    - dfu-tool.wrapper
    - fwupd-command
    - fwupdtool.wrapper
    - fwupd.wrapper
    - fwupdmgr.wrapper
