name: fwupd
adopt-info: fwupd
summary: A standalone version of fwupd to install newer firmware updates
description: |
  This is a tool that can be used to install firmware updates on devices
  not yet supported by the version of fwupd distributed with the OS.

grade: stable
confinement: classic
base: core22

architectures:
  - amd64

apps:
  dfu-tool:
    command: dfu-tool.wrapper
  dbxtool:
    command: dbxtool.wrapper
  fwupdtool:
    command: fwupdtool.wrapper
    completer:
      share/bash-completion/completions/fwupdtool
  fwupd:
    command: fwupd.wrapper
    daemon: simple
  fwupdmgr:
    command: fwupdmgr.wrapper
    completer:
      share/bash-completion/completions/fwupdmgr
  fwupdagent:
    command: fwupdagent.wrapper

parts:
  #fetch the latest version of the signed bootloader
  #this might not match our fwupdx64.efi, but it's better than nothing
  fwup-efi-signed:
    build-packages:
      - python3-apt
    plugin: make
    source: contrib/snap/fwup-efi-signed
  #needed for UEFI plugin to build UX labels
  build-introspection:
    plugin: nil
    stage-packages:
      - python3-gi
      - python3-cairo
    prime:
      - -etc
      - -usr
      - -var
  fwupd:
    plugin: meson
    meson-parameters: [--prefix=/,
                       -Defi_binary=false,
                       -Dplugin_uefi_capsule_splash=false,
                       -Dtests=false,
                       -Dbuild=all,
                       -Dintrospection=disabled,
                       -Dman=false,
                       -Dplugin_powerd=disabled,
                       -Dudevdir=$SNAPCRAFT_STAGE/lib/udev,
                       "-Dgusb:tests=false",
                       "-Dgusb:docs=false",
                       "-Dgusb:introspection=false",
                       "-Dgusb:vapi=false",
                       "-Dlibxmlb:gtkdoc=false",
                       "-Dlibxmlb:introspection=false",
                       "-Dlibjcat:man=false",
                       "-Dlibjcat:gtkdoc=false",
                       "-Dlibjcat:introspection=false",
                       "-Dlibjcat:tests=false"]
    source: .
    source-type: git
    override-build: |
      snapcraftctl build
      echo $(git describe HEAD --always) > $SNAPCRAFT_STAGE/version
      for name in ${SNAPCRAFT_PART_INSTALL}/lib/*/fwupd-*/libfwupd*; do
        mv ${name} `dirname ${name}`/.. ;\
      done
      # fixes up commands like fwupdtool -> fwupd.fwupdtool
      sed -i "s,\(complete -F _fwupd[a-z]*\) \(fwupd.*\),\1 fwupd.\2,;          \
              s,\(command.*\)\(fwupdtool\),\1fwupd.\2,;                         \
              s,\(command.*\)\(fwupdmgr\),\1fwupd.\2,;                          \
              s,\(command.*\)\(fwupdagent\),\1fwupd.\2,"                        \
              ${SNAPCRAFT_PART_INSTALL}/share/bash-completion/completions/*
      # fixes up dbus service for classic snap
      sed -i 's!SystemdService=\(.*\)!SystemdService=snap.fwupd.fwupd.service!' \
              ${SNAPCRAFT_PART_INSTALL}/share/dbus-1/system-services/org.freedesktop.fwupd.service
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe HEAD --always)
    build-packages:
      - bash-completion
      - curl
      - gettext
      - gcab
      - gnu-efi
      - libcurl4-openssl-dev
      - libarchive-dev
      - libcbor-dev
      - libcairo-dev
      - libefiboot-dev
      - libefivar-dev
      - libflashrom-dev
      - libftdi1-dev
      - libgudev-1.0-dev
      - libgcab-dev
      - libglib2.0-dev
      - libgnutls28-dev
      - libgpgme11-dev
      - libgusb-dev
      - libjson-glib-dev
      - libjcat-dev
      - liblzma-dev
      - libpango1.0-dev
      - libpci-dev
      - libpolkit-gobject-1-dev
      - libprotobuf-c-dev
      - libsmbios-dev
      - libsqlite3-dev
      - libsystemd-dev
      - libtss2-dev
      - libxmlb-dev
      - libmm-glib-dev
      - libqmi-glib-dev
      - libmbim-glib-dev
      - locales
      - meson
      - modemmanager
      - pkg-config
      - python3-cairo
      - python3-gi
      - protobuf-c-compiler
      - systemd
      - uuid-dev
    stage-packages:
      - libgcab-1.0-0
      - libarchive13
      - libcurl4
      - libcbor0.8
      - libassuan0
      - libflashrom1
      - libjcat1
      - liblcms2-2
      - liblzma5
      - libefivar1
      - libefiboot1
      - libgusb2
      - libusb-1.0-0
      - libgudev-1.0-0
      - libgpgme11
      - libpolkit-gobject-1-0
      - libsmbios-c2
      - libtss2-esys-3.0.2-0
      - libtss2-fapi1
      - libtss2-mu0
      - libtss2-rc0
      - libtss2-sys1
      - libtss2-tcti-cmd0
      - libtss2-tcti-device0
      - libtss2-tcti-mssim0
      - libtss2-tcti-swtpm0
      - libtss2-tctildr0
      - libxmlb2
      - glib-networking
      - libglib2.0-bin
      - libglib2.0-0
    prime:
      # we explicitly don't want /usr/bin/gpgconf
      # this will cause gpgme to error finding it
      # but that also avoids trying to use non-existent
      # /usr/bin/gpg2
      - -usr/bin
      - -usr/sbin
      - -usr/share/man
      - -usr/share/GConf
      - -etc/X11
      - -etc/ldap
      - -etc/logcheck
      - -usr/lib/dconf
      - -usr/lib/gcc
      - -usr/lib/glib-networking
      - -usr/lib/gnupg2
      - -usr/lib/sasl2
      - -usr/lib/systemd
      - -usr/lib/*/audit
      - -usr/share/glib-2.0/schemas
      - -usr/share/X11
      - -include
      - -lib/udev
      - -lib/*/pkgconfig
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/installed-tests
      - -usr/share/polkit-1
      - -usr/share/vala
      - -usr/share/doc
      - -usr/share/gnupg2
      - -usr/share/info
      - -usr/share/gir-1.0
      - -usr/share/upstart
      - -usr/lib/*/pkgconfig
    after: [build-introspection]
  activate-shutdown:
    plugin: make
    source: contrib/snap/activate-shutdown
    after: [fwupd]
  update-mime:
    plugin: make
    source: contrib/snap/update-mime
    stage-packages:
      - shared-mime-info
      - gsettings-desktop-schemas
      - libxml2
    prime:
      - -usr/bin
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/man
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/GConf
    after: [fwupd]
  fwupd-wrappers:
    plugin: dump
    source: contrib/snap
    stage:
    - dfu-tool.wrapper
    - dbxtool.wrapper
    - fwupd-command
    - fwupdtool.wrapper
    - fwupd.wrapper
    - fwupdmgr.wrapper
    - fwupdagent.wrapper
