.\" Report problems in https://github.com/fwupd/fwupd
.TH man 8 "11 April 2021" @PACKAGE_VERSION@ "fwupdtpmevlog man page"
.SH NAME
fwupdtpmevlog \- debugging utility for the TPM event log
.SH SYNOPSIS
fwupdtpmevlog [CMD]
.SH DESCRIPTION
This tool will read and parse the TPM event log from the system firmware.
.SH OPTIONS
The fwupdtpmevlog command takes various options depending on the action.
Run \fBfwupdtpmevlog --help\fR for the full list.
.SH SEE ALSO
fwupdtool(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Richard Hughes (richard@hughsie.com)
