/*
 * Copyright 2026 Red Hat
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */

// Feel free to edit this file, it won't be regenerated by gir generator unless removed.

#include <fwupdplugin.h>

// The GIR scanner picks up types from private and generated headers via the
// .c source files. Include all private and generated struct headers so the
// ABI validation test can compile against the full set of types.

// Private headers
#include <fu-backend-private.h>
#include <fu-bios-settings-private.h>
#include <fu-cab-firmware-private.h>
#include <fu-cbor-item-private.h>
#include <fu-chunk-private.h>
#include <fu-common-private.h>
#include <fu-config-private.h>
#include <fu-context-private.h>
#include <fu-crc-private.h>
#include <fu-csv-firmware-private.h>
#include <fu-device-event-private.h>
#include <fu-device-private.h>
#include <fu-dfu-firmware-private.h>
#include <fu-drm-device-private.h>
#include <fu-efi-signature-private.h>
#include <fu-efi-x509-signature-private.h>
#include <fu-efivars-private.h>
#include <fu-firmware-private.h>
#include <fu-hwids-private.h>
#include <fu-ioctl-private.h>
#include <fu-kernel-search-path-private.h>
#include <fu-mem-private.h>
#include <fu-msgpack-item-private.h>
#include <fu-partial-input-stream-private.h>
#include <fu-plugin-private.h>
#include <fu-progress-private.h>
#include <fu-security-attrs-private.h>
#include <fu-smbios-private.h>
#include <fu-udev-device-private.h>
#include <fu-uefi-device-private.h>
#include <fu-usb-bos-descriptor-private.h>
#include <fu-usb-config-descriptor-private.h>
#include <fu-usb-device-private.h>
#include <fu-usb-endpoint-private.h>
#include <fu-usb-hid-descriptor-private.h>
#include <fu-usb-interface-private.h>
#include <fu-volume-private.h>

// Internal headers (not private, not public, but referenced by GIR)
#include <fu-device-progress.h>
#include <fu-efi-common.h>
#include <fu-tpm-eventlog-common.h>
#include <fu-usb-device-ds20.h>
#include <fu-usb-device-fw-ds20.h>
#include <fu-usb-device-ms-ds20.h>

// Generated struct headers (from rustgen)
#include <fu-acpi-table-struct.h>
#include <fu-cab-struct.h>
#include <fu-cbor-struct.h>
#include <fu-cfi-struct.h>
#include <fu-cfu-firmware-struct.h>
#include <fu-cfu-struct.h>
#include <fu-common-struct.h>
#include <fu-config-struct.h>
#include <fu-context-struct.h>
#include <fu-coswid-struct.h>
#include <fu-crc-struct.h>
#include <fu-device-struct.h>
#include <fu-dfu-firmware-struct.h>
#include <fu-dpaux-struct.h>
#include <fu-dump-struct.h>
#include <fu-edid-struct.h>
#include <fu-efi-struct.h>
#include <fu-elf-struct.h>
#include <fu-fdt-struct.h>
#include <fu-firmware-struct.h>
#include <fu-fmap-struct.h>
#include <fu-heci-struct.h>
#include <fu-hid-struct.h>
#include <fu-ifd-struct.h>
#include <fu-ifwi-struct.h>
#include <fu-ihex-struct.h>
#include <fu-intel-me-struct.h>
#include <fu-intel-thunderbolt-struct.h>
#include <fu-io-channel-struct.h>
#include <fu-ioctl-struct.h>
#include <fu-msgpack-struct.h>
#include <fu-oprom-struct.h>
#include <fu-path-struct.h>
#include <fu-pci-struct.h>
#include <fu-pefile-struct.h>
#include <fu-processor-struct.h>
#include <fu-progress-struct.h>
#include <fu-protobuf-struct.h>
#include <fu-quirks-struct.h>
#include <fu-sbatlevel-section-struct.h>
#include <fu-security-attrs-struct.h>
#include <fu-smbios-struct.h>
#include <fu-srec-struct.h>
#include <fu-tpm-struct.h>
#include <fu-usb-device-ds20-struct.h>
#include <fu-usb-struct.h>
#include <fu-uswid-struct.h>
#include <fu-v4l-struct.h>
#include <fu-zip-struct.h>
