on: workflow_call

permissions:
  contents: read

jobs:
  freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build
        uses: vmactions/freebsd-vm@83b151f58c6047089f4c80eb5ba2039d158ce093 # v1.5.3
        env:
          CC: gcc
        with:
          usesh: true
          mem: 8192
          sync: rsync
          envs: "CI CC"
          prepare: |
            pkg install -y bash python3 git ninja cmake gcc
          run: |
            ./contrib/ci/fwupd_setup_helpers.py install-dependencies -o freebsd --yes
            ./contrib/setup
            bash -c "source ./venv/bin/activate && build-fwupd"
