name: clang-tidy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fwupd/fwupd/fwupd-ubuntu-amd64:latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |-
          apt-get update -qq
          apt-get install -qq --yes --no-install-recommends clang-tidy rustc
          ./contrib/ci/fwupd_setup_helpers.py install-pip --yes -o ubuntu
          ./contrib/ci/fwupd_setup_helpers.py test-meson
      - name: configure
        run: |-
          meson setup -Dwerror=true build
      - name: build
        run: |-
          ninja -C build
      - name: clang-tidy
        run: |-
          ninja -C build clang-tidy
