name: Create containers
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  push_to_registry:
    permissions:
      packages: write # for docker/build-push-action
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        distro: [arch, centos, debian, debian-i386, debian-tartan, fedora, ubuntu]
        runner: [ubuntu-latest]
        cross: [null]
        include:
          - distro: debian
            runner: ubuntu-latest
            cross: i386
          - distro: debian
            runner: ubuntu-24.04-arm
            cross: null
          - distro: debian
            runner: ubuntu-24.04-arm
            cross: s390x
          - distro: precommit
            runner: ubuntu-24.04-arm
            cross: null
    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Generate Dockerfile"
        env:
          MATRIX_CROSS: ${{ matrix.cross || '' }}
          TARGET_DISTRO: ${{ matrix.distro }}
          RUNNER_ARCH: ${{ runner.arch }}
        run: ./contrib/ci/generate_docker.py
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          push: true
          tags: "ghcr.io/fwupd/fwupd/fwupd-${{ matrix.distro }}${{ case(contains(matrix.distro, '-'), '', runner.arch == 'ARM64', '-arm64', '-amd64') }}${{ case(matrix.cross != null, format('-cross-{0}', matrix.cross), '') }}:latest"
