name: FreeBSD daily Builds
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-freebsd:
    runs-on: macos-10.15
    timeout-minutes: 30
    name: build-freebsd-package
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Find tag
      id: tagger
      uses: jimschubert/query-tag-action@v2
    - name: Build
      id: test
      uses: vmactions/freebsd-vm@v0.2.0
      with:
        usesh: true
        mem: 8192
        prepare: |
          pkg install -y git python3 glib meson pkgconf gobject-introspection \
            vala gtk-doc json-glib gpgme gnutls sqlite3 curl gcab libarchive \
            libgpg-error gettext-tools gtk-update-icon-cache atk pango \
            binutils gcc protobuf-c libcbor
        sync: rsync
        run: ./contrib/ci/build_freebsd_package.sh
          --GITHUB_SHA=${GITHUB_SHA}
          --GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER}
          --GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
          --GITHUB_TAG=${{steps.tagger.outputs.tag}}
    - name: Upload fwupd binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: Binary package
        path: |
          fwupd*.pkg

