name: GObject Lint
on: [pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bilelmoussaoui/gobject-linter:latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - name: Run gobject-linter
        run: gobject-linter
