name: GObject Lint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bilelmoussaoui/goblint:latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - name: Run goblint
        run: goblint
