name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your contribution!'
        pr-message: 'We really appreciate new contributors to the fwupd project. Please review https://github.com/fwupd/fwupd/blob/main/CONTRIBUTING.md for details on how to effectively write patches for pull requests.'
