name: Pull Request reviews
on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-24.04-arm
    env:
      SKIP: no-commit-to-branch
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up APT caching
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: pre-commit-apt-${{ runner.os }}-${{ hashFiles('.github/workflows/*.yml') }}
          restore-keys: pre-commit-apt-${{ runner.os }}-
      - name: Set up pre-commit
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends \
            -o APT::Keep-Downloaded-Packages=true \
            -o Binary::apt::APT::Keep-Downloaded-Packages=true \
            black \
            clang-format \
            codespell \
            git \
            gitleaks \
            markdownlint \
            meson \
            patch \
            pre-commit \
            shellcheck \
            shfmt
      - name: Run pre-commit hooks
        run: pre-commit run -v --show-diff-on-failure --hook-stage commit --all-files

  snap:
    needs: pre-commit
    uses: ./.github/workflows/snap.yml
    with:
      deploy: false
    secrets: inherit

  matrix:
    needs: pre-commit
    uses: ./.github/workflows/matrix.yml
    with:
      publish: false
    secrets: inherit
