name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-windows:
    name: Publish Windows binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        id: download
        with:
          name: windows
      - name: Populate release body
        id: read_release
        shell: bash
        run: |
          r=$(cat dist/news.txt)
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT
      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: dist/setup/*.msi
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}  # <--- Use environment variables that was created earlier
