name: Snap workflow
on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  build-snap:
    runs-on: ubuntu-latest
    outputs:
      snap_name: ${{ steps.snapcraft.outputs.snap }}
      channel: ${{ steps.channel.outputs.channel }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - id: channel
        run: |
          if git describe --exact-match; then
            echo "channel=candidate" >> $GITHUB_OUTPUT
          else
            echo "channel=edge" >> $GITHUB_OUTPUT
          fi
      - id: prep
        run: |
          mkdir -p snap
          ln -s ../contrib/snap/snapcraft.yaml snap/snapcraft.yaml
      - uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 # v1.3.0
        id: snapcraft
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
