name: Publish to snap candidate channel

on:
  release:
    types: [published]

jobs:
  snap:
    uses: ./.github/workflows/snap.yml
    with:
      deploy:  true
      channel: candidate
    secrets: inherit

