#!/bin/sh -e

install_if_missing() {
	if [ "$2" != "/" ]; then
		mkdir -p $(dirname ${2}/${1})
	fi
	install -m 644 -C ${SNAP}/${1} ${2}/${1}
}

#install policykit rules and actions
install_if_missing share/polkit-1/actions/org.freedesktop.fwupd.policy /usr
install_if_missing share/polkit-1/rules.d/org.freedesktop.fwupd.rules /usr
#install dbus related items
install_if_missing share/dbus-1/system-services/org.freedesktop.fwupd.service /usr
install_if_missing share/dbus-1/interfaces/org.freedesktop.fwupd.xml /usr
install_if_missing share/dbus-1/system.d/org.freedesktop.fwupd.conf /usr
#activation via systemd
install_if_missing etc/systemd/system/fwupd-activate.service /
systemctl daemon-reload
systemctl enable fwupd-activate
systemctl start fwupd-activate
