#!/bin/sh -e

#activation via systemd
systemctl stop fwupd-activate
systemctl disable fwupd-activate
rm /etc/systemd/system/fwupd-activate.service -f
systemctl daemon-reload
#msr module
rm /usr/lib/modules-load.d/fwupd-msr.conf -f
#optional grub configuration
rm /etc/grub.d/35_fwupd -f
