#!/bin/sh -e

#offline updates
rm /etc/systemd/system/fwupd-offline-update.service -f
rm /etc/systemd/system/system-update.target.wants/fwupd-offline-update.service -f
rm /etc/systemd/system/system-update.target.wants/snap.fwupd.fwupd.service -f
#activation via systemd
systemctl stop fwupd-activate
systemctl disable fwupd-activate
rm /etc/systemd/system/fwupd-activate.service -f
systemctl daemon-reload
